// 大河の一滴 — 水循環ノードグラフ
//
// このゲームは物語を大量に書くのではなく、水循環のネットワークを作る。
// ノードを足せばそのままゲーム世界が広がる。正解ルートも失敗ルートも存在しない。

import type { RegionId, RunState, Tag, WaterNode } from "./types";

const inRegion =
  (...ids: RegionId[]) =>
  (s: RunState) =>
    ids.includes(s.region);

const exceptRegion =
  (...ids: RegionId[]) =>
  (s: RunState) =>
    !ids.includes(s.region);

const hasTag =
  (t: Tag) =>
  (s: RunState) =>
    s.tags.includes(t);

const YEAR = 8766;
const DAY = 24;

const list: WaterNode[] = [
  // ───────────────────────────────────────────── 空
  {
    id: "CLOUD_BIRTH",
    name: "雲の中",
    place: "上空 2,400m",
    biome: "sky",
    phase: "liquid",
    scene: "cloud",
    lines: [
      "白い光の中を、無数の水滴が漂っている。",
      "そのうちの一つが、あなたです。",
      "少しずつ重くなり、まわりの水滴とぶつかりながら、雲の底へ沈んでいく。",
    ],
    hours: [0.5, 8],
    km: [1, 30],
    altitude: 2400,
    temperature: 3,
    tags: ["sky"],
    codex: "cloud",
    choices: [
      {
        label: "北の風に乗る",
        detail: "冷たい空気の層へ横滑りしていく。",
        outcomes: [{ to: "SKY_COLD", weight: 3 }, { to: "SKY_FALL" }],
      },
      {
        label: "そのまま落ちる",
        detail: "重さにまかせて、雲の底を抜ける。",
        outcomes: [{ to: "SKY_FALL" }],
      },
      {
        label: "上昇気流に乗る",
        detail: "下から突き上げる暖かい柱に持ち上げられる。",
        outcomes: [{ to: "SKY_UPDRAFT" }],
      },
    ],
  },
  {
    id: "SKY_UPDRAFT",
    name: "上昇気流",
    place: "積乱雲の内側",
    biome: "sky",
    phase: "liquid",
    scene: "sky",
    lines: [
      "空気の柱が、真下から突き上げてくる。",
      "雲の天井へ運ばれる。空気が薄い。まわりが急に冷たくなる。",
    ],
    hours: [0.2, 4],
    km: [2, 18],
    altitude: 9000,
    temperature: -22,
    tags: ["sky"],
    choices: [
      {
        label: "凍りついて重くなる",
        detail: "まわりの水を巻き込み、氷の粒が育つ。",
        outcomes: [{ to: "SKY_HAIL" }],
      },
      {
        label: "さらに高くへ",
        detail: "雲の天井、氷の粒だけが残る高さへ。",
        outcomes: [{ to: "SKY_ANVIL" }],
      },
      {
        label: "気流から外れる",
        detail: "柱の縁でこぼれ落ちる。",
        outcomes: [{ to: "SKY_FALL", weight: 3 }, { to: "CLOUD_BIRTH" }],
      },
    ],
  },
  {
    id: "SKY_ANVIL",
    name: "雲の天井",
    place: "上空 11,000m",
    biome: "sky",
    phase: "solid",
    scene: "sky",
    lines: [
      "もう水ではない。六角形の氷の結晶になっている。",
      "眼下に、雲の海が果てしなく広がっている。",
    ],
    hours: [1, 30],
    km: [10, 220],
    altitude: 11000,
    temperature: -46,
    tags: ["sky", "snow"],
    codex: "icecrystal",
    choices: [
      {
        label: "枝を伸ばして雪になる",
        detail: "まわりの水蒸気が結晶にくっつき、大きくなっていく。",
        outcomes: [{ to: "SNOWFALL" }],
      },
      {
        label: "ジェット気流に乗る",
        detail: "時速200kmの川が、空の高いところを流れている。",
        outcomes: [{ to: "SKY_JET" }],
      },
    ],
  },
  {
    id: "SKY_JET",
    name: "ジェット気流",
    place: "対流圏界面",
    biome: "sky",
    phase: "solid",
    scene: "sky",
    lines: [
      "空にも川がある。",
      "地図でしか見たことのない海岸線が、下を流れ去っていく。",
    ],
    hours: [8, 90],
    km: [900, 4200],
    altitude: 11500,
    temperature: -52,
    tags: ["sky", "snow"],
    choices: [
      {
        label: "気流を降りる",
        detail: "速度を失い、ゆっくり落ちはじめる。",
        outcomes: [{ to: "SNOWFALL", weight: 2 }, { to: "SKY_FALL" }],
      },
      {
        label: "もう少し運ばれる",
        detail: "大陸を一つ越えてしまうかもしれない。",
        outcomes: [{ to: "SKY_COLD", weight: 2 }, { to: "SKY_JET" }],
      },
    ],
  },
  {
    id: "SKY_HAIL",
    name: "あられ",
    place: "雲の底",
    biome: "sky",
    phase: "solid",
    scene: "snowfall",
    lines: [
      "氷の層が何重にも巻きつき、重くなった。",
      "もう気流では支えきれない。落ちる。速い。",
    ],
    hours: [0.05, 0.4],
    km: [2, 5],
    altitude: 1200,
    temperature: -3,
    tags: ["sky", "snow"],
    codex: "hail",
    choices: [
      {
        label: "落ちながら溶ける",
        detail: "地表付近の暖かい空気に、外側から削られていく。",
        outcomes: [{ to: "SKY_FALL" }],
      },
      {
        label: "氷のまま地面へ",
        detail: "屋根を、葉を、雪の上を叩く音になる。",
        outcomes: [
          { to: "SNOW_PACK", weight: 2 },
          { to: "CITY_ROOF", when: exceptRegion("antarctic", "arctic", "pacific") },
          { to: "FOREST_FLOOR", weight: 2 },
        ],
      },
    ],
  },
  {
    id: "SKY_COLD",
    name: "冷たい空気の層",
    place: "上空",
    biome: "sky",
    phase: "liquid",
    scene: "sky",
    lines: [
      "北から来た空気は、乾いていて、重い。",
      "体がわずかに固くなるのがわかる。",
    ],
    hours: [0.5, 12],
    km: [20, 400],
    altitude: 3200,
    temperature: -8,
    tags: ["sky"],
    choices: [
      {
        label: "結晶になる",
        detail: "ひとつの核を中心に、水蒸気が六方向へ並びはじめる。",
        outcomes: [{ to: "SNOWFALL" }],
      },
      {
        label: "液体のまま落ちる",
        detail: "凍る寸前の、ぎりぎりの温度で降りていく。",
        outcomes: [{ to: "SKY_FALL" }],
      },
    ],
  },
  {
    id: "SNOWFALL",
    name: "雪",
    place: "降雪の中",
    biome: "sky",
    phase: "solid",
    scene: "snowfall",
    lines: [
      "落ちているという感覚がない。",
      "ただ、下からゆっくり世界が近づいてくる。音が、ない。",
    ],
    hours: [0.5, 6],
    km: [2, 20],
    altitude: 900,
    temperature: -4,
    tags: ["sky", "snow"],
    codex: "snow",
    choices: [
      {
        label: "山の斜面へ",
        detail: "白い尾根が、すぐ下にある。",
        outcomes: [{ to: "SNOW_PACK" }],
      },
      {
        label: "森の上へ",
        detail: "黒い針葉樹の梢が、雪を受け止めようと広がっている。",
        outcomes: [{ to: "FOREST_SNOW" }],
        when: exceptRegion("antarctic", "pacific"),
      },
      {
        label: "凍った海の上へ",
        detail: "白い平原に見えるが、その下は数千mの海。",
        outcomes: [{ to: "SEA_ICE" }],
        when: inRegion("arctic", "antarctic", "pacific"),
      },
      {
        label: "街の明かりへ",
        detail: "灰色の屋根の上に、静かに積もっていく。",
        outcomes: [{ to: "CITY_SNOW" }],
        when: inRegion("japan", "himalaya"),
      },
    ],
  },
  {
    id: "SKY_FALL",
    name: "落下",
    place: "地上へ",
    biome: "sky",
    phase: "liquid",
    scene: "rainfall",
    lines: [
      "空気に押されて、丸から、少しつぶれた形へ。",
      "地表が近づいてくる。もう戻れない。",
    ],
    hours: [0.05, 0.5],
    km: [1, 4],
    altitude: 500,
    temperature: 12,
    tags: ["sky"],
    codex: "rain",
    choices: [
      {
        label: "山の斜面へ吸い寄せられる",
        detail: "上昇する風が、山肌のほうへ押し戻してくる。",
        outcomes: [
          { to: "MTN_ROCK", weight: 2 },
          { to: "MTN_MOSS" },
          { to: "MTN_SCREE" },
        ],
        when: exceptRegion("pacific", "sahel"),
      },
      {
        label: "緑の濃いほうへ",
        detail: "葉が幾重にも重なって、地面が見えない。",
        outcomes: [
          { to: "FOREST_LEAF", weight: 3 },
          { to: "FOREST_BRANCH" },
          { to: "FOREST_FLOOR" },
        ],
        when: exceptRegion("pacific", "antarctic", "arctic"),
      },
      {
        label: "光の集まるほうへ",
        detail: "四角い形ばかりが並ぶ、平らな場所。",
        outcomes: [
          { to: "CITY_ROOF", weight: 2 },
          { to: "CITY_ROAD" },
          { to: "CITY_PARK" },
        ],
        when: inRegion("japan", "seasia"),
      },
      {
        label: "ひらけた土のほうへ",
        detail: "区切られた四角い地面が、地平線まで続いている。",
        outcomes: [
          { to: "PLAIN_SOIL", weight: 2 },
          { to: "PADDY", when: inRegion("japan", "seasia") },
          { to: "POND" },
        ],
        when: exceptRegion("antarctic", "arctic", "pacific"),
      },
      {
        label: "水面の照り返しへ",
        detail: "空を映した、平らで巨大な面。",
        outcomes: [
          { to: "OCEAN_SURFACE", weight: 3, when: inRegion("pacific", "arctic", "antarctic", "seasia") },
          { to: "LAKE_SURFACE", weight: 2 },
        ],
      },
    ],
  },

  // ───────────────────────────────────────────── 山
  {
    id: "MTN_ROCK",
    name: "岩肌",
    place: "山地・稜線",
    biome: "mountain",
    phase: "liquid",
    scene: "mountain",
    lines: [
      "硬い。灰色の岩に当たって、飛沫が散る。",
      "その一つとして、あなたは岩の表面に残った。",
    ],
    hours: [0.2, 6],
    km: [0, 0.4],
    altitude: 1900,
    temperature: 6,
    tags: ["mountain"],
    codex: "bedrock",
    choices: [
      {
        label: "岩の割れ目へ入る",
        detail: "髪の毛ほどの隙間が、暗く奥へ続いている。",
        outcomes: [{ to: "GW_FISSURE" }],
      },
      {
        label: "斜面を流れ落ちる",
        detail: "他の水と合わさりながら、いちばん低いほうへ。",
        outcomes: [{ to: "MTN_STREAM", weight: 3 }, { to: "MTN_SCREE" }],
      },
      {
        label: "日なたで温まる",
        detail: "岩が熱を持っている。体が軽くなっていく。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "MTN_SCREE",
    name: "ガレ場",
    place: "山地・崩落斜面",
    biome: "mountain",
    phase: "liquid",
    scene: "scree",
    lines: [
      "拳ほどの石が、斜面いっぱいに散らばっている。",
      "石と石のあいだには、いくらでも隙間がある。",
    ],
    hours: [1, 40],
    km: [0.1, 2],
    altitude: 1600,
    temperature: 7,
    tags: ["mountain"],
    choices: [
      {
        label: "石の下へ潜り込む",
        detail: "日の当たらない、冷たい隙間の奥へ。",
        outcomes: [{ to: "SOIL_SHALLOW", weight: 2 }, { to: "GW_GRAVEL" }],
      },
      {
        label: "石の上を伝う",
        detail: "細い流れが、石の面を選びながら下っていく。",
        outcomes: [{ to: "MTN_STREAM" }],
      },
      {
        label: "苔のほうへ",
        detail: "岩の北側だけが、緑に濡れている。",
        outcomes: [{ to: "MTN_MOSS" }],
      },
    ],
  },
  {
    id: "MTN_MOSS",
    name: "苔",
    place: "山地・岩壁",
    biome: "mountain",
    phase: "liquid",
    scene: "moss",
    lines: [
      "無数の細い葉が、あなたを掴んで離さない。",
      "苔は水をためる。ここは、山の小さな貯水池だ。",
    ],
    hours: [2, 200],
    km: [0, 0.2],
    altitude: 1500,
    temperature: 8,
    tags: ["mountain", "plant"],
    codex: "moss",
    choices: [
      {
        label: "苔にたっぷり抱えられる",
        detail: "雨が止んでも、ここはしばらく濡れている。",
        outcomes: [{ to: "MTN_MOSS_HOLD" }],
      },
      {
        label: "重みで滴り落ちる",
        detail: "限界まで水を含んだ苔から、一滴ぶんだけこぼれる。",
        outcomes: [{ to: "MTN_STREAM", weight: 2 }, { to: "SOIL_SHALLOW" }],
      },
      {
        label: "陽が差して蒸発する",
        detail: "霧が晴れる。緑が一気に明るくなる。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "MTN_MOSS_HOLD",
    name: "苔のなか",
    place: "山地・岩壁",
    biome: "mountain",
    phase: "liquid",
    scene: "moss",
    lines: [
      "季節がひとつ、通り過ぎた。",
      "苔は乾き、また濡れ、そのたびにあなたを離さなかった。",
    ],
    hours: [200, 2600],
    km: [0, 0.1],
    altitude: 1500,
    temperature: 9,
    tags: ["mountain", "plant"],
    choices: [
      {
        label: "霧に溶ける",
        detail: "苔の表面から、目に見えないほど静かに空へ。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "岩を伝って落ちる",
        detail: "大雨が来た。苔が支えきれなくなる。",
        outcomes: [{ to: "MTN_STREAM", weight: 2 }, { to: "GW_FISSURE" }],
      },
    ],
  },
  {
    id: "MTN_STREAM",
    name: "沢",
    place: "山地・源流",
    biome: "river",
    phase: "liquid",
    scene: "stream",
    lines: [
      "幅は、たったの数十センチ。",
      "けれど確かに流れている。ここが、川のいちばん上。",
    ],
    hours: [1, 60],
    km: [0.5, 6],
    altitude: 1200,
    temperature: 7,
    tags: ["mountain", "stream"],
    codex: "brook",
    choices: [
      {
        label: "他の沢と合わさる",
        detail: "向こうからも、同じような細い流れが来ている。",
        outcomes: [{ to: "BROOK" }],
      },
      {
        label: "河床の砂利へ潜る",
        detail: "流れの一部は、川底の下を流れている。",
        outcomes: [{ to: "GW_GRAVEL", weight: 2 }, { to: "SOIL_SHALLOW" }],
      },
      {
        label: "落ち込みへ",
        detail: "岩の段差。下は白く泡立っている。",
        outcomes: [{ to: "WATERFALL", weight: 2 }, { to: "RAPIDS" }],
      },
    ],
  },
  {
    id: "MTN_SNOWFIELD",
    name: "雪渓",
    place: "山地・谷筋",
    biome: "cryo",
    phase: "solid",
    scene: "snowfield",
    lines: [
      "夏になっても、この谷の雪は消えない。",
      "上から押され、下から融け、雪はゆっくり谷を下っている。",
    ],
    hours: [DAY * 60, DAY * 900],
    km: [0.05, 0.6],
    altitude: 2100,
    temperature: -1,
    tags: ["mountain", "snow"],
    codex: "snowfield",
    timeflow: true,
    choices: [
      {
        label: "融けて谷底へ",
        detail: "雪渓の下では、いつも水が流れる音がしている。",
        outcomes: [{ to: "MELTWATER" }],
      },
      {
        label: "押し固められる",
        detail: "上に積もる雪の重さで、粒と粒の境目が消えていく。",
        outcomes: [{ to: "FIRN" }],
      },
      {
        label: "そのまま空へ",
        detail: "強い日射と乾いた風。氷は、液体を経ずに消えることがある。",
        outcomes: [{ to: "SUBLIMATION" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 雪・氷
  {
    id: "SNOW_PACK",
    name: "積雪",
    place: "山地・雪原",
    biome: "cryo",
    phase: "solid",
    scene: "snowfield",
    lines: [
      "着地の音はしなかった。",
      "何億という結晶の一つとして、白い層に加わる。",
    ],
    hours: [DAY * 3, DAY * 200],
    km: [0, 0.3],
    altitude: 2000,
    temperature: -6,
    tags: ["snow"],
    codex: "snowpack",
    choices: [
      {
        label: "日当たりのよい斜面へ",
        detail: "南向きの面は、春がいちばん早く来る。",
        outcomes: [{ to: "MELTWATER", weight: 3 }, { to: "SNOW_SUN" }],
      },
      {
        label: "風で谷へ吹き飛ばされる",
        detail: "尾根の雪は、風にとって運びやすい荷物でしかない。",
        outcomes: [{ to: "MTN_SNOWFIELD", weight: 2 }, { to: "SNOW_DEEP" }],
      },
      {
        label: "雪原の底に残る",
        detail: "上に降り続ける雪が、あなたを深く埋めていく。",
        outcomes: [{ to: "SNOW_DEEP" }],
      },
    ],
  },
  {
    id: "SNOW_SUN",
    name: "陽だまりの雪",
    place: "山地・南斜面",
    biome: "cryo",
    phase: "solid",
    scene: "snowfield",
    lines: [
      "表面が、きらきらと濡れはじめている。",
      "夜になるとまた凍る。それを何十回もくり返した。",
    ],
    hours: [DAY * 5, DAY * 90],
    km: [0, 0.2],
    altitude: 1800,
    temperature: 0,
    tags: ["snow"],
    choices: [
      {
        label: "融けて流れ出す",
        detail: "雪の下に、透明な水路ができている。",
        outcomes: [{ to: "MELTWATER" }],
      },
      {
        label: "空気に直接消える",
        detail: "乾いた晴天。氷から、いきなり水蒸気へ。",
        outcomes: [{ to: "SUBLIMATION" }],
      },
    ],
  },
  {
    id: "SNOW_DEEP",
    name: "雪の底",
    place: "積雪層の下部",
    biome: "cryo",
    phase: "solid",
    scene: "snowfield",
    lines: [
      "上の雪の重さで、結晶の枝が折れ、丸くなっていく。",
      "光はもう、ほとんど届かない。青い。",
    ],
    hours: [DAY * 60, DAY * 700],
    km: [0, 0.4],
    altitude: 1900,
    temperature: -4,
    tags: ["snow"],
    timeflow: true,
    choices: [
      {
        label: "万年雪になる",
        detail: "夏を越えた雪は、もう雪と呼ばれない。",
        outcomes: [{ to: "FIRN" }],
      },
      {
        label: "春を待って融ける",
        detail: "層の底から、水がしみ出していく。",
        outcomes: [{ to: "MELTWATER", weight: 2 }, { to: "SOIL_SHALLOW" }],
      },
    ],
  },
  {
    id: "FIRN",
    name: "万年雪",
    place: "涵養域",
    biome: "cryo",
    phase: "solid",
    scene: "glacier",
    lines: [
      "雪でもなく、まだ氷でもない。",
      "粒のあいだの空気が、少しずつ追い出されていく。",
    ],
    hours: [YEAR * 3, YEAR * 60],
    km: [0.1, 3],
    altitude: 2600,
    temperature: -9,
    tags: ["snow", "glacier"],
    timeflow: true,
    choices: [
      {
        label: "氷になる",
        detail: "最後の空気が泡として閉じ込められ、透明になる。",
        outcomes: [{ to: "GLACIER" }],
      },
      {
        label: "夏に融けて逃げる",
        detail: "例年より暑い夏が、何度か続いた。",
        outcomes: [{ to: "MELTWATER" }],
      },
    ],
  },
  {
    id: "GLACIER",
    name: "氷河",
    place: "氷河の内部",
    biome: "cryo",
    phase: "solid",
    scene: "glacier",
    lines: [
      "動けない。",
      "けれど、氷そのものが谷を下っている。一年に、数十メートル。",
      "あなたのまわりの気泡は、あなたが降った日の空気だ。",
    ],
    hours: [YEAR * 40, YEAR * 3000],
    km: [0.5, 25],
    altitude: 2200,
    depth: 120,
    temperature: -14,
    tags: ["glacier"],
    codex: "glacier",
    timeflow: true,
    choices: [
      {
        label: "末端まで運ばれる",
        detail: "谷の下では、氷の壁が崩れる音がしている。",
        outcomes: [
          { to: "MELTWATER", weight: 3 },
          { to: "GLACIER_CALVING", when: inRegion("arctic", "antarctic") },
        ],
      },
      {
        label: "もっと深くへ沈む",
        detail: "毎年降る雪が、あなたを氷床の底へ押し下げる。",
        outcomes: [{ to: "ICE_SHEET" }],
      },
      {
        label: "表面に現れる",
        detail: "氷が削れて、何百年ぶりかに空が見える。",
        outcomes: [{ to: "SUBLIMATION", weight: 2 }, { to: "MELTWATER" }],
      },
    ],
  },
  {
    id: "ICE_SHEET",
    name: "氷床の底",
    place: "氷床 深度 2,800m",
    biome: "cryo",
    phase: "solid",
    scene: "glacier",
    lines: [
      "音楽が止まる。",
      "上に積もった氷の重さは、数千メートル分。",
      "あなたが空から落ちてきたとき、地上に人はまだ、ほとんどいなかった。",
    ],
    hours: [YEAR * 8000, YEAR * 900000],
    km: [1, 60],
    altitude: 200,
    depth: 2800,
    temperature: -32,
    tags: ["glacier"],
    codex: "icesheet",
    timeflow: true,
    choices: [
      {
        label: "気候が変わるのを待つ",
        detail: "できることは、なにもない。ただ、待つ。",
        outcomes: [{ to: "GLACIER_CALVING", weight: 2 }, { to: "MELTWATER" }],
      },
      {
        label: "底面で融ける",
        detail: "地球の内側から届く熱が、氷床の底をわずかに融かしている。",
        outcomes: [{ to: "SUBGLACIAL_LAKE" }],
      },
    ],
  },
  {
    id: "SUBGLACIAL_LAKE",
    name: "氷底湖",
    place: "氷床の下",
    biome: "cryo",
    phase: "liquid",
    scene: "lakedeep",
    lines: [
      "何千mもの氷の下に、凍っていない水がある。",
      "真っ暗で、静かで、何百万年も外気に触れていない。",
    ],
    hours: [YEAR * 1000, YEAR * 200000],
    km: [0.5, 40],
    depth: 3600,
    temperature: -2,
    tags: ["glacier", "deepwater"],
    codex: "subglacial",
    timeflow: true,
    choices: [
      {
        label: "氷の割れ目へ押し出される",
        detail: "圧力が、水をゆっくり横へ押している。",
        outcomes: [{ to: "GLACIER_CALVING", weight: 2 }, { to: "OCEAN_DEEP" }],
      },
      {
        label: "さらに留まる",
        detail: "この水が次に空を見るのは、いつだろう。",
        outcomes: [{ to: "ICE_SHEET" }],
      },
    ],
  },
  {
    id: "GLACIER_CALVING",
    name: "氷が割れる",
    place: "氷河末端",
    biome: "cryo",
    phase: "solid",
    scene: "seaice",
    lines: [
      "亀裂が走る音が、地面ごと響いた。",
      "氷の壁が、海へ倒れていく。",
      "何万年ぶりかの、まぶしさ。",
    ],
    hours: [DAY * 30, YEAR * 6],
    km: [5, 900],
    temperature: -1,
    salinity: "saline",
    tags: ["glacier", "ocean", "seaice"],
    choices: [
      {
        label: "海に漂って融ける",
        detail: "氷山の底から、冷たい淡水がほどけていく。",
        outcomes: [{ to: "OCEAN_SURFACE", weight: 2 }, { to: "OCEAN_DEEP" }],
      },
      {
        label: "海氷に閉じ込められる",
        detail: "冬が来た。海そのものが凍りはじめる。",
        outcomes: [{ to: "SEA_ICE" }],
      },
    ],
  },
  {
    id: "SEA_ICE",
    name: "海氷",
    place: "極海・氷の下",
    biome: "cryo",
    phase: "solid",
    scene: "seaice",
    lines: [
      "海が凍るとき、塩は氷から追い出される。",
      "残されたのは、ほとんど真水のあなただ。",
    ],
    hours: [DAY * 60, YEAR * 9],
    km: [10, 1400],
    temperature: -12,
    salinity: "fresh",
    tags: ["seaice", "ocean"],
    codex: "seaice",
    timeflow: true,
    choices: [
      {
        label: "海流に運ばれる",
        detail: "氷そのものが、巨大な筏になって海を渡っている。",
        outcomes: [{ to: "OCEAN_CURRENT", weight: 2 }, { to: "SEA_ICE" }],
      },
      {
        label: "夏に融ける",
        detail: "白かった世界に、黒い水の割れ目が広がっていく。",
        outcomes: [{ to: "OCEAN_SURFACE" }],
      },
      {
        label: "雪に埋もれる",
        detail: "海氷の上に降った雪が、また層をつくる。",
        outcomes: [{ to: "SNOW_DEEP", weight: 2 }, { to: "SEA_ICE" }],
      },
    ],
  },
  {
    id: "PERMAFROST",
    name: "永久凍土",
    place: "凍土層 深度 12m",
    biome: "cryo",
    phase: "solid",
    scene: "permafrost",
    lines: [
      "土と氷が、区別できないほど混ざり合っている。",
      "夏でも、ここは融けない。少なくとも、今までは。",
    ],
    hours: [YEAR * 200, YEAR * 40000],
    km: [0, 2],
    depth: 12,
    temperature: -7,
    tags: ["permafrost", "groundwater"],
    codex: "permafrost",
    timeflow: true,
    choices: [
      {
        label: "融けて地表へ",
        detail: "地面が沈み、湖ができる。凍土が緩んでいる。",
        outcomes: [{ to: "TUNDRA_POOL" }],
      },
      {
        label: "さらに深く凍る",
        detail: "寒い時代がもう一度めぐってきた。",
        outcomes: [{ to: "PERMAFROST", weight: 1 }, { to: "GW_DEEP", weight: 2 }],
      },
    ],
  },
  {
    id: "TUNDRA_POOL",
    name: "ツンドラの池",
    place: "凍土帯",
    biome: "lake",
    phase: "liquid",
    scene: "wetland",
    lines: [
      "地平線まで、無数の小さな池が散らばっている。",
      "水は下へ行けない。凍土が、ふたをしているから。",
    ],
    hours: [DAY * 20, YEAR * 12],
    km: [0, 3],
    temperature: 4,
    tags: ["permafrost", "wetland", "lake"],
    choices: [
      {
        label: "白夜の光で蒸発する",
        detail: "太陽が沈まない季節が、短く、強く続く。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "川へ抜ける",
        detail: "池と池がつながり、北の海をめざす流れになる。",
        outcomes: [{ to: "RIVER_MAIN" }],
      },
      {
        label: "また凍る",
        detail: "九月。水面に、薄い膜が張った。",
        outcomes: [{ to: "PERMAFROST" }],
      },
    ],
  },
  {
    id: "MELTWATER",
    name: "融雪水",
    place: "雪解けの斜面",
    biome: "cryo",
    phase: "liquid",
    scene: "stream",
    lines: [
      "固まっていた体が、ほどける。",
      "何十年ぶりかに、動ける。",
    ],
    hours: [1, 200],
    km: [0.5, 12],
    altitude: 1400,
    temperature: 2,
    tags: ["snow", "stream"],
    codex: "meltwater",
    choices: [
      {
        label: "沢に合流する",
        detail: "白く濁った水が、いくつも合わさっていく。",
        outcomes: [{ to: "MTN_STREAM", weight: 2 }, { to: "BROOK" }],
      },
      {
        label: "土に染み込む",
        detail: "雪の下の地面は、水を待っていた。",
        outcomes: [{ to: "SOIL_SHALLOW", weight: 2 }, { to: "GW_GRAVEL" }],
      },
      {
        label: "湖へ流れ込む",
        detail: "谷底に、雪解けで濁った青がたまっている。",
        outcomes: [{ to: "LAKE_SURFACE" }],
      },
    ],
  },
  {
    id: "SUBLIMATION",
    name: "昇華",
    place: "氷の表面",
    biome: "sky",
    phase: "gas",
    scene: "vapor",
    lines: [
      "融けなかった。",
      "氷のまま、いきなり空気になった。",
      "液体だった時間が、一度もない。",
    ],
    hours: [0.1, 3],
    km: [0.1, 3],
    temperature: -10,
    tags: ["sublimation", "vapor"],
    codex: "sublimation",
    choices: [
      {
        label: "空へのぼる",
        detail: "乾いた冷たい空気の中を、まっすぐ上へ。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 森
  {
    id: "FOREST_LEAF",
    name: "ブナの葉",
    place: "森・林冠",
    biome: "forest",
    phase: "liquid",
    scene: "leaf",
    lines: [
      "巨大な緑の皿に受け止められた。",
      "葉脈が、川の地図のように張りめぐらされている。",
      "あなたの丸い表面に、森が逆さまに映っている。",
    ],
    hours: [0.2, 8],
    km: [0, 0.05],
    altitude: 700,
    temperature: 17,
    tags: ["forest", "plant"],
    codex: "leaf",
    choices: [
      {
        label: "葉先へ転がる",
        detail: "葉のいちばん低いところに、水が集まる仕組みになっている。",
        outcomes: [{ to: "FOREST_DRIP" }],
      },
      {
        label: "葉の表面に残る",
        detail: "動かない。ただ、そこにいる。",
        outcomes: [{ to: "FOREST_SUN" }],
      },
      {
        label: "枝のほうへ流れる",
        detail: "葉の付け根から、太い道が幹へ続いている。",
        outcomes: [{ to: "FOREST_BRANCH" }],
      },
    ],
  },
  {
    id: "FOREST_SUN",
    name: "葉の上の陽",
    place: "森・林冠",
    biome: "forest",
    phase: "liquid",
    scene: "leaf",
    lines: [
      "雲が切れた。太陽が出る。",
      "葉が温まり、あなたの縁から、形がほどけはじめる。",
    ],
    hours: [0.5, 4],
    km: [0, 0.02],
    altitude: 700,
    temperature: 26,
    tags: ["forest", "plant"],
    choices: [
      {
        label: "蒸発する",
        detail: "とても短い一生だった。けれど、終わりではない。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "風でこぼれ落ちる",
        detail: "梢が揺れる。葉が傾く。",
        outcomes: [{ to: "FOREST_DRIP", weight: 2 }, { to: "FOREST_FLOOR" }],
      },
    ],
  },
  {
    id: "FOREST_DRIP",
    name: "葉先のしずく",
    place: "森・林床の上",
    biome: "forest",
    phase: "liquid",
    scene: "canopy",
    lines: [
      "葉先で、限界まで引き伸ばされる。",
      "落ちる。下は、何百年ぶんもの落ち葉。",
    ],
    hours: [0.01, 0.3],
    km: [0.01, 0.03],
    altitude: 690,
    temperature: 16,
    tags: ["forest"],
    choices: [
      {
        label: "腐葉土へ落ちる",
        detail: "柔らかく、暗く、生きものの匂いがする層。",
        outcomes: [{ to: "FOREST_FLOOR" }],
      },
      {
        label: "苔の上へ落ちる",
        detail: "倒木を覆う、緑のじゅうたん。",
        outcomes: [{ to: "FOREST_MOSS" }],
      },
      {
        label: "窪みの水たまりへ",
        detail: "木の根元に、小さな鏡ができている。",
        outcomes: [{ to: "FOREST_POOL" }],
      },
    ],
  },
  {
    id: "FOREST_BRANCH",
    name: "枝を伝う水",
    place: "森・樹幹",
    biome: "forest",
    phase: "liquid",
    scene: "canopy",
    lines: [
      "枝の下側を、細い筋になって進む。",
      "樹皮の割れ目が、そのまま水路になっている。",
    ],
    hours: [0.1, 3],
    km: [0.01, 0.05],
    altitude: 690,
    temperature: 16,
    tags: ["forest", "plant"],
    choices: [
      {
        label: "幹を伝って根元へ",
        detail: "雨のたび、木は自分の根元に水を集めている。",
        outcomes: [{ to: "FOREST_ROOT", weight: 2 }, { to: "FOREST_FLOOR" }],
      },
      {
        label: "樹皮の窪みに溜まる",
        detail: "枝の分かれ目に、小さな水たまりができている。",
        outcomes: [{ to: "FOREST_HOLLOW" }],
      },
      {
        label: "途中でこぼれる",
        detail: "風。枝が跳ねる。",
        outcomes: [{ to: "FOREST_DRIP" }],
      },
    ],
  },
  {
    id: "FOREST_HOLLOW",
    name: "樹洞の水",
    place: "森・樹上",
    biome: "forest",
    phase: "liquid",
    scene: "canopy",
    lines: [
      "枝の分かれ目の窪みに、小さな水たまりができている。",
      "落ち葉と、虫と、あなた。地上5mの、独立した池。",
    ],
    hours: [DAY, DAY * 60],
    km: [0, 0.01],
    altitude: 695,
    temperature: 18,
    tags: ["forest", "life"],
    choices: [
      {
        label: "鳥に飲まれる",
        detail: "くちばしが、水面を割った。",
        outcomes: [{ to: "ANIMAL_BODY" }],
      },
      {
        label: "干上がる",
        detail: "晴天が続く。水位が、日ごとに下がっていく。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "溢れて幹を伝う",
        detail: "大雨。窪みが満ちて、外へこぼれる。",
        outcomes: [{ to: "FOREST_ROOT", weight: 2 }, { to: "FOREST_FLOOR" }],
      },
    ],
  },
  {
    id: "FOREST_MOSS",
    name: "森の苔",
    place: "森・倒木",
    biome: "forest",
    phase: "liquid",
    scene: "moss",
    lines: [
      "倒れた木が、緑に覆われている。",
      "苔は根を持たない。体の表面から、直接あなたを吸い込む。",
    ],
    hours: [2, 400],
    km: [0, 0.05],
    altitude: 680,
    temperature: 15,
    tags: ["forest", "plant"],
    codex: "moss",
    choices: [
      {
        label: "苔の中で待つ",
        detail: "乾けば眠り、濡れれば起きる。苔の時間はゆっくりだ。",
        outcomes: [{ to: "VAPOR_RISE", weight: 2 }, { to: "FOREST_FLOOR" }],
      },
      {
        label: "倒木の内側へ",
        detail: "木は朽ちて、スポンジのようになっている。",
        outcomes: [{ to: "FOREST_FLOOR", weight: 2 }, { to: "SOIL_SHALLOW" }],
      },
    ],
  },
  {
    id: "FOREST_POOL",
    name: "森の水たまり",
    place: "森・林床",
    biome: "forest",
    phase: "liquid",
    scene: "forestfloor",
    lines: [
      "木漏れ日が、水面で揺れている。",
      "小さな虫が、あなたの上を滑っていった。",
    ],
    hours: [3, 600],
    km: [0, 0.05],
    altitude: 660,
    temperature: 16,
    tags: ["forest"],
    choices: [
      {
        label: "地面に吸われる",
        detail: "水たまりの底から、静かに減っていく。",
        outcomes: [{ to: "FOREST_FLOOR", weight: 2 }, { to: "SOIL_SHALLOW" }],
      },
      {
        label: "動物に飲まれる",
        detail: "四本の脚が近づいてきて、影が水面を覆った。",
        outcomes: [{ to: "ANIMAL_BODY" }],
      },
      {
        label: "陽に温められる",
        detail: "浅い水は、すぐに温まる。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "FOREST_FLOOR",
    name: "腐葉土",
    place: "森・林床",
    biome: "forest",
    phase: "liquid",
    scene: "forestfloor",
    lines: [
      "落ち葉の間を抜け、暗い土の中へ。",
      "何年も前の葉が、少しずつ土になっていく途中の層。",
      "菌糸が、白い糸のように張りめぐらされている。",
    ],
    hours: [2, 300],
    km: [0, 0.3],
    altitude: 650,
    temperature: 13,
    tags: ["forest", "soil"],
    codex: "litter",
    choices: [
      {
        label: "深く染み込む",
        detail: "重力にまかせて、土の粒のあいだを下っていく。",
        outcomes: [{ to: "SOIL_SHALLOW", weight: 2 }, { to: "SOIL_DEEP" }],
      },
      {
        label: "斜面を流れる",
        detail: "染み込みきらなかった水が、落ち葉の下を走る。",
        outcomes: [{ to: "FOREST_RUNOFF" }],
      },
      {
        label: "木の根へ",
        detail: "太い根が、地面の下で腕を広げている。",
        outcomes: [{ to: "FOREST_ROOT" }],
      },
    ],
  },
  {
    id: "FOREST_RUNOFF",
    name: "落ち葉の下の流れ",
    place: "森・斜面",
    biome: "forest",
    phase: "liquid",
    scene: "forestfloor",
    lines: [
      "地表を、うっすらとした膜になって滑っていく。",
      "土は削らない。落ち葉が、地面を守っている。",
    ],
    hours: [0.5, 24],
    km: [0.05, 2],
    altitude: 600,
    temperature: 14,
    tags: ["forest"],
    choices: [
      {
        label: "沢へ出る",
        detail: "水の音が、だんだん大きくなってくる。",
        outcomes: [{ to: "MTN_STREAM", weight: 2 }, { to: "BROOK" }],
      },
      {
        label: "途中で吸い込まれる",
        detail: "モグラの穴。根の跡。土には、無数の抜け道がある。",
        outcomes: [{ to: "SOIL_SHALLOW" }],
      },
    ],
  },
  {
    id: "FOREST_ROOT",
    name: "木の根",
    place: "森・根圏",
    biome: "life",
    phase: "liquid",
    scene: "treeinside",
    lines: [
      "細い根の先が、あなたを掴む。",
      "膜を通り抜ける。もう、外の水ではない。",
    ],
    hours: [0.5, 12],
    km: [0.01, 0.1],
    altitude: 650,
    temperature: 14,
    tags: ["forest", "plant", "life"],
    codex: "root",
    choices: [
      {
        label: "幹をのぼる",
        detail: "細い管の列を、上へ、上へ。木は水を引き上げている。",
        outcomes: [{ to: "TREE_TRUNK" }],
      },
      {
        label: "根に留まる",
        detail: "細胞の中に取り込まれる。しばらく、木そのものになる。",
        outcomes: [{ to: "TREE_CELL" }],
      },
    ],
  },
  {
    id: "TREE_TRUNK",
    name: "幹の中",
    place: "樹木・道管",
    biome: "life",
    phase: "liquid",
    scene: "treeinside",
    lines: [
      "直径わずか0.1mmの管を、切れ目のない糸になって上昇する。",
      "引っぱっているのは、いちばん上の葉だ。",
    ],
    hours: [0.5, 20],
    km: [0.01, 0.04],
    altitude: 670,
    temperature: 15,
    tags: ["plant", "life"],
    codex: "xylem",
    choices: [
      {
        label: "葉へ運ばれる",
        detail: "枝分かれのたび、道は細くなっていく。",
        outcomes: [{ to: "TREE_STOMA" }],
      },
      {
        label: "実のほうへ",
        detail: "枝先に、重い実がぶら下がっている。",
        outcomes: [{ to: "TREE_FRUIT" }],
      },
    ],
  },
  {
    id: "TREE_CELL",
    name: "細胞の中",
    place: "樹木・柔組織",
    biome: "life",
    phase: "liquid",
    scene: "treeinside",
    lines: [
      "膜に囲まれた小さな部屋に、閉じ込められた。",
      "この木の一部として、季節をいくつか過ごす。",
    ],
    hours: [DAY * 20, DAY * 900],
    km: [0, 0.02],
    temperature: 14,
    tags: ["plant", "life"],
    timeflow: true,
    choices: [
      {
        label: "また流れに戻る",
        detail: "細胞が壊れ、水が管へ返される。",
        outcomes: [{ to: "TREE_TRUNK", weight: 2 }, { to: "TREE_STOMA" }],
      },
      {
        label: "木とともに倒れる",
        detail: "寿命。あるいは、風。木が地面に横たわる。",
        outcomes: [{ to: "FOREST_FLOOR" }],
      },
    ],
  },
  {
    id: "TREE_FRUIT",
    name: "実の中",
    place: "樹木・果実",
    biome: "life",
    phase: "liquid",
    scene: "treeinside",
    lines: [
      "甘い水になった。",
      "果実の90%は、水でできている。",
    ],
    hours: [DAY * 10, DAY * 120],
    km: [0, 0.01],
    temperature: 18,
    tags: ["plant", "life"],
    codex: "fruit",
    choices: [
      {
        label: "動物に食べられる",
        detail: "歯が、果肉を裂いた。",
        outcomes: [{ to: "ANIMAL_BODY" }],
      },
      {
        label: "落ちて土に還る",
        detail: "熟しきった実が、林床で潰れる。",
        outcomes: [{ to: "FOREST_FLOOR" }],
      },
    ],
  },
  {
    id: "TREE_STOMA",
    name: "気孔",
    place: "樹木・葉の裏",
    biome: "life",
    phase: "gas",
    scene: "leaf",
    lines: [
      "葉の裏に、唇の形をした小さな穴が並んでいる。",
      "そこが開いた瞬間、あなたは水蒸気になって外へ出た。",
      "蒸散。木は、根から吸った水のほとんどを空へ返している。",
    ],
    hours: [0.05, 1],
    km: [0.01, 0.1],
    altitude: 700,
    temperature: 22,
    tags: ["plant", "life", "vapor"],
    codex: "stoma",
    choices: [
      {
        label: "森の上へのぼる",
        detail: "森全体から立ちのぼる湿気が、白い帯になっている。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "林内の霧になる",
        detail: "木々のあいだに、白いものが漂いはじめる。",
        outcomes: [{ to: "MIST" }],
      },
    ],
  },
  {
    id: "FOREST_SNOW",
    name: "梢の雪",
    place: "森・林冠",
    biome: "forest",
    phase: "solid",
    scene: "snowfall",
    lines: [
      "針葉樹の枝に、そっと乗った。",
      "枝がしなる。まだ落ちない。",
    ],
    hours: [DAY, DAY * 60],
    km: [0, 0.02],
    altitude: 720,
    temperature: -3,
    tags: ["forest", "snow"],
    choices: [
      {
        label: "枝から落ちる",
        detail: "音もなく、林床の雪の上へ。",
        outcomes: [{ to: "SNOW_PACK", weight: 2 }, { to: "FOREST_FLOOR" }],
      },
      {
        label: "枝の上で消える",
        detail: "冬の乾いた風が、氷を直接さらっていく。",
        outcomes: [{ to: "SUBLIMATION" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 平原・農地
  {
    id: "PLAIN_SOIL",
    name: "畑の土",
    place: "平野・耕作地",
    biome: "plain",
    phase: "liquid",
    scene: "plain",
    lines: [
      "耕された土は、やわらかく、水を通しやすい。",
      "まっすぐ下へ、あるいは根のほうへ。",
    ],
    hours: [1, 200],
    km: [0, 0.5],
    altitude: 90,
    temperature: 16,
    tags: ["plain", "soil"],
    codex: "farmsoil",
    choices: [
      {
        label: "作物の根へ",
        detail: "細い根毛が、土の粒にまとわりついている。",
        outcomes: [{ to: "CROP_ROOT" }],
      },
      {
        label: "深く浸透する",
        detail: "耕された層を抜けると、締まった土が待っている。",
        outcomes: [{ to: "SOIL_DEEP", weight: 2 }, { to: "GW_GRAVEL" }],
      },
      {
        label: "地表を流れる",
        detail: "強い雨。土が吸いきれなかった水が、畑の畝を越える。",
        outcomes: [{ to: "IRRIGATION", weight: 2 }, { to: "POND" }],
      },
    ],
  },
  {
    id: "CROP_ROOT",
    name: "作物の中",
    place: "平野・耕作地",
    biome: "life",
    phase: "liquid",
    scene: "treeinside",
    lines: [
      "小さな植物の、細い茎をのぼる。",
      "この水は、やがて誰かの食べものになる。",
    ],
    hours: [DAY, DAY * 90],
    km: [0, 0.02],
    temperature: 20,
    tags: ["plant", "life"],
    choices: [
      {
        label: "葉から蒸散する",
        detail: "昼のあいだ、畑は静かに空へ水を返し続けている。",
        outcomes: [{ to: "TREE_STOMA" }],
      },
      {
        label: "実に蓄えられる",
        detail: "収穫され、運ばれ、台所へ。",
        outcomes: [{ to: "TREE_FRUIT", weight: 2 }, { to: "HUMAN_BODY" }],
      },
    ],
  },
  {
    id: "PADDY",
    name: "水田",
    place: "平野・水田",
    biome: "plain",
    phase: "liquid",
    scene: "paddy",
    lines: [
      "浅く、広く、温かい水。",
      "空が、そっくりそのまま映っている。",
      "この水面は、人間が水循環の途中に作った、平らな湖だ。",
    ],
    hours: [DAY * 3, DAY * 120],
    km: [0, 1],
    altitude: 40,
    temperature: 24,
    tags: ["plain", "paddy", "human"],
    codex: "paddy",
    choices: [
      {
        label: "稲に吸い上げられる",
        detail: "無数の細い茎が、水田じゅうに立っている。",
        outcomes: [{ to: "CROP_ROOT" }],
      },
      {
        label: "地下へ抜ける",
        detail: "水田の底からは、いつも少しずつ水が漏れている。",
        outcomes: [{ to: "GW_GRAVEL", weight: 2 }, { to: "SOIL_DEEP" }],
      },
      {
        label: "水面から蒸発する",
        detail: "夏の午後。田んぼ一枚が、白く霞んで見える。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "IRRIGATION",
    name: "農業用水路",
    place: "平野・用水路",
    biome: "human",
    phase: "liquid",
    scene: "canal",
    lines: [
      "コンクリートで固められた、まっすぐな道。",
      "流れの速さも、行き先も、人間が決めている。",
    ],
    hours: [2, 300],
    km: [1, 40],
    altitude: 50,
    temperature: 18,
    tags: ["human", "plain"],
    codex: "canal",
    choices: [
      {
        label: "水田へ引かれる",
        detail: "板を一枚外すだけで、水は行き先を変える。",
        outcomes: [{ to: "PADDY" }],
      },
      {
        label: "ため池へ入る",
        detail: "使われない水が、いったん貯められる。",
        outcomes: [{ to: "POND" }],
      },
      {
        label: "川へ戻される",
        detail: "使い終わった水路の先は、たいてい川につながっている。",
        outcomes: [{ to: "RIVER_MAIN" }],
      },
    ],
  },
  {
    id: "POND",
    name: "ため池",
    place: "平野・ため池",
    biome: "lake",
    phase: "liquid",
    scene: "pond",
    lines: [
      "藻が濃く、水底は見えない。",
      "小さな魚が、あなたの横を通り過ぎていく。",
    ],
    hours: [DAY * 5, DAY * 400],
    km: [0, 1],
    altitude: 45,
    temperature: 21,
    tags: ["lake"],
    codex: "pond",
    choices: [
      {
        label: "魚のえらを通る",
        detail: "口から入り、赤い櫛のような器官を抜けていく。",
        outcomes: [{ to: "FISH_GILL" }],
      },
      {
        label: "水面から蒸発する",
        detail: "風のない朝。水面から、白いものが立ちのぼる。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "底から地下へ",
        detail: "池の底は、思ったより水を通す。",
        outcomes: [{ to: "SOIL_DEEP", weight: 2 }, { to: "GW_GRAVEL" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 都市
  {
    id: "CITY_ROOF",
    name: "屋根",
    place: "市街地・屋上",
    biome: "city",
    phase: "liquid",
    scene: "city",
    lines: [
      "傾いた平面に当たって、まっすぐ縁へ走らされる。",
      "この街には、水が染み込める場所がほとんどない。",
    ],
    hours: [0.05, 2],
    km: [0.005, 0.05],
    altitude: 45,
    temperature: 19,
    tags: ["city", "human"],
    codex: "roof",
    choices: [
      {
        label: "雨樋へ吸い込まれる",
        detail: "細い管が、屋根じゅうの水を一点に集めている。",
        outcomes: [{ to: "CITY_DRAIN" }],
      },
      {
        label: "熱いスレートで蒸発する",
        detail: "日が差した。屋根が、みるみる乾いていく。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "雨水タンクへ",
        detail: "この建物は、屋根の水をためている。",
        outcomes: [{ to: "CITY_TANK" }],
      },
    ],
  },
  {
    id: "CITY_ROAD",
    name: "アスファルト",
    place: "市街地・路面",
    biome: "city",
    phase: "liquid",
    scene: "city",
    lines: [
      "黒く、熱く、水を1ミリも通さない面。",
      "タイヤが、あなたを跳ね上げていった。",
    ],
    hours: [0.05, 3],
    km: [0.01, 0.3],
    altitude: 40,
    temperature: 24,
    tags: ["city", "human"],
    codex: "road",
    choices: [
      {
        label: "路肩の側溝へ",
        detail: "道の端は、そのために少しだけ低く作られている。",
        outcomes: [{ to: "CITY_DRAIN" }],
      },
      {
        label: "街路樹の根元へ",
        detail: "四角く切り取られた土。街で数少ない、水の入口。",
        outcomes: [{ to: "CITY_PARK" }],
      },
      {
        label: "路面で干上がる",
        detail: "陽が戻る。濡れた黒が、乾いた灰色に変わっていく。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "CITY_PARK",
    name: "公園の土",
    place: "市街地・公園",
    biome: "city",
    phase: "liquid",
    scene: "city",
    lines: [
      "コンクリートに囲まれた、小さな土の島。",
      "踏み固められてはいるが、それでも水は入っていける。",
    ],
    hours: [1, 200],
    km: [0, 0.4],
    altitude: 38,
    temperature: 18,
    tags: ["city", "soil"],
    choices: [
      {
        label: "地下へ染み込む",
        detail: "街の下にも、ちゃんと地下水は流れている。",
        outcomes: [{ to: "SOIL_SHALLOW", weight: 2 }, { to: "GW_URBAN" }],
      },
      {
        label: "木の根に吸われる",
        detail: "ケヤキの根が、舗装の下まで伸びている。",
        outcomes: [{ to: "FOREST_ROOT" }],
      },
      {
        label: "水たまりに残る",
        detail: "窪みに溜まった水を、子どもが踏んで割った。",
        outcomes: [{ to: "CITY_PUDDLE" }],
      },
    ],
  },
  {
    id: "CITY_PUDDLE",
    name: "水たまり",
    place: "市街地",
    biome: "city",
    phase: "liquid",
    scene: "city",
    lines: [
      "アスファルトの窪みに、空が映っている。",
      "ビルが、逆さまに立っている。",
    ],
    hours: [1, 40],
    km: [0, 0.02],
    altitude: 38,
    temperature: 22,
    tags: ["city"],
    choices: [
      {
        label: "蒸発する",
        detail: "夕方には、跡だけが残っていた。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "跳ねて排水溝へ",
        detail: "車が通る。あなたは宙を飛んだ。",
        outcomes: [{ to: "CITY_DRAIN" }],
      },
    ],
  },
  {
    id: "CITY_SNOW",
    name: "街の雪",
    place: "市街地",
    biome: "city",
    phase: "solid",
    scene: "snowfall",
    lines: [
      "灰色の街が、一晩で白くなった。",
      "音が吸い込まれて、いつもより静かだ。",
    ],
    hours: [DAY, DAY * 20],
    km: [0, 0.2],
    altitude: 40,
    temperature: -2,
    tags: ["city", "snow"],
    choices: [
      {
        label: "融けて排水溝へ",
        detail: "除雪された雪の山が、黒く汚れながら小さくなっていく。",
        outcomes: [{ to: "CITY_DRAIN" }],
      },
      {
        label: "屋根の上で凍る",
        detail: "夜のあいだに、軒先に氷柱が育った。",
        outcomes: [{ to: "CITY_ROOF", weight: 2 }, { to: "SUBLIMATION" }],
      },
    ],
  },
  {
    id: "CITY_TANK",
    name: "雨水タンク",
    place: "市街地・貯留槽",
    biome: "human",
    phase: "liquid",
    scene: "waterworks",
    lines: [
      "暗く、冷たい、大きな箱。",
      "街が水浸しにならないよう、雨をいったん預かる装置。",
    ],
    hours: [DAY, DAY * 200],
    km: [0, 0.1],
    altitude: 30,
    temperature: 17,
    tags: ["human", "city"],
    codex: "reservoir",
    choices: [
      {
        label: "撒き水に使われる",
        detail: "夏の夕方、屋上の植栽へ。",
        outcomes: [{ to: "CITY_PARK", weight: 2 }, { to: "VAPOR_RISE" }],
      },
      {
        label: "ゆっくり放流される",
        detail: "雨がやんでから、少しずつ下水管へ送り出される。",
        outcomes: [{ to: "CITY_SEWER" }],
      },
    ],
  },
  {
    id: "CITY_DRAIN",
    name: "排水溝",
    place: "市街地・雨水枡",
    biome: "city",
    phase: "liquid",
    scene: "drain",
    lines: [
      "鉄の格子の隙間に吸い込まれ、暗闇へ落ちる。",
      "街の下に、もう一つの街があった。",
    ],
    hours: [0.05, 2],
    km: [0.05, 1],
    altitude: 30,
    depth: 4,
    temperature: 18,
    tags: ["city", "human"],
    codex: "drain",
    choices: [
      {
        label: "雨水管を下る",
        detail: "雨だけを集める管。行き先は、たいてい近くの川。",
        outcomes: [{ to: "CITY_STORM" }],
      },
      {
        label: "下水管に合流する",
        detail: "生活の水と混ざる。匂いが、いっきに濃くなる。",
        outcomes: [{ to: "CITY_SEWER" }],
      },
      {
        label: "地下調整池へ",
        detail: "巨大な柱が並ぶ、地下の空間。都市の水を受け止める場所。",
        outcomes: [{ to: "CITY_CISTERN" }],
      },
    ],
  },
  {
    id: "CITY_CISTERN",
    name: "地下調整池",
    place: "地下 50m",
    biome: "human",
    phase: "liquid",
    scene: "waterworks",
    lines: [
      "コンクリートの柱が、暗闇の奥まで並んでいる。",
      "神殿のようだ。人間は、水を止めるためにここまで作った。",
    ],
    hours: [2, DAY * 20],
    km: [0.2, 3],
    depth: 50,
    temperature: 17,
    tags: ["human", "city"],
    codex: "cistern",
    choices: [
      {
        label: "ポンプで川へ返される",
        detail: "雨がやんだ。巨大なポンプが動きはじめる。",
        outcomes: [{ to: "RIVER_MAIN" }],
      },
      {
        label: "下水処理場へ送られる",
        detail: "汚れた初期雨水は、そのまま川へは戻せない。",
        outcomes: [{ to: "SEWAGE_PLANT" }],
      },
    ],
  },
  {
    id: "CITY_STORM",
    name: "雨水管",
    place: "地下・雨水幹線",
    biome: "human",
    phase: "liquid",
    scene: "sewer",
    lines: [
      "直径3mの円い空間を、猛烈な速さで走っている。",
      "声が、何度も反射して返ってくる。",
    ],
    hours: [0.1, 4],
    km: [0.5, 12],
    depth: 8,
    temperature: 18,
    tags: ["human", "city"],
    choices: [
      {
        label: "吐口から川へ",
        detail: "急に空が開けた。護岸の穴から、濁った水が噴き出す。",
        outcomes: [{ to: "RIVER_MAIN", weight: 2 }, { to: "ESTUARY" }],
      },
      {
        label: "溢れて下水と混ざる",
        detail: "雨が強すぎた。管の容量を超えている。",
        outcomes: [{ to: "CITY_SEWER" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 地下
  {
    id: "SOIL_SHALLOW",
    name: "土壌水",
    place: "地下 0.4m",
    biome: "underground",
    phase: "liquid",
    scene: "soil",
    lines: [
      "土の粒と粒のあいだ、髪の毛より細い隙間に挟まれている。",
      "重力で下へ引かれ、同時に、土の表面に引き止められている。",
    ],
    hours: [DAY, DAY * 120],
    km: [0, 0.5],
    depth: 0.4,
    temperature: 13,
    tags: ["soil", "groundwater"],
    codex: "soilwater",
    choices: [
      {
        label: "さらに下へ",
        detail: "根が届かない深さまで抜ければ、もう戻ってこない。",
        outcomes: [{ to: "SOIL_DEEP" }],
      },
      {
        label: "根に吸い上げられる",
        detail: "土の中に、白い根毛が無数に伸びている。",
        outcomes: [{ to: "FOREST_ROOT", weight: 2 }, { to: "CROP_ROOT" }],
      },
      {
        label: "地表へ戻る",
        detail: "土が乾く。毛細管が、水を上へ引き上げていく。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "SOIL_DEEP",
    name: "深い土",
    place: "地下 4m",
    biome: "underground",
    phase: "liquid",
    scene: "soil",
    lines: [
      "土の色が変わった。赤茶けた層。粘土。",
      "ここから先は、もう植物の手は届かない。",
    ],
    hours: [DAY * 10, DAY * 900],
    km: [0, 1],
    depth: 4,
    temperature: 14,
    tags: ["soil", "groundwater"],
    timeflow: true,
    choices: [
      {
        label: "砂礫層へ抜ける",
        detail: "粘土の層を抜けると、急に隙間の多い世界になる。",
        outcomes: [{ to: "GW_GRAVEL" }],
      },
      {
        label: "岩の割れ目へ",
        detail: "硬い岩盤に、細い亀裂が走っている。",
        outcomes: [{ to: "GW_FISSURE" }],
      },
      {
        label: "粘土に阻まれ横へ",
        detail: "下へ行けない水は、傾きにしたがって横に流れる。",
        outcomes: [{ to: "SPRING", weight: 2 }, { to: "SOIL_SHALLOW" }],
      },
    ],
  },
  {
    id: "GW_GRAVEL",
    name: "砂礫層",
    place: "地下 18m",
    biome: "underground",
    phase: "liquid",
    scene: "aquifer",
    lines: [
      "丸い石と砂の隙間を、迷路のように進む。",
      "速い、といっても、一日に数十センチ。",
    ],
    hours: [DAY * 30, YEAR * 8],
    km: [0.05, 3],
    depth: 18,
    temperature: 14,
    tags: ["groundwater"],
    codex: "shallow_gw",
    timeflow: true,
    choices: [
      {
        label: "帯水層の奥へ",
        detail: "地下の巨大なスポンジ。地球でいちばん大きな淡水の貯金箱。",
        outcomes: [{ to: "GW_AQUIFER" }],
      },
      {
        label: "湧水として出る",
        detail: "地層が地表と交わる場所が、すぐ先にある。",
        outcomes: [{ to: "SPRING" }],
      },
      {
        label: "井戸に引き寄せられる",
        detail: "遠くで、水が一方向へ引かれている。ポンプだ。",
        outcomes: [{ to: "WELL" }],
        when: exceptRegion("antarctic", "arctic", "pacific"),
      },
    ],
  },
  {
    id: "GW_FISSURE",
    name: "岩の割れ目",
    place: "地下 60m",
    biome: "underground",
    phase: "liquid",
    scene: "deeprock",
    lines: [
      "岩は水を通さない、というのは正しくない。",
      "どんな岩にも、ひびがある。水は、そこを通る。",
    ],
    hours: [YEAR, YEAR * 60],
    km: [0.1, 6],
    depth: 60,
    temperature: 16,
    tags: ["groundwater"],
    timeflow: true,
    choices: [
      {
        label: "石灰岩を溶かしながら進む",
        detail: "水は岩を削るだけでなく、少しずつ溶かしてもいる。",
        outcomes: [{ to: "CAVE" }],
      },
      {
        label: "もっと深くへ落ちる",
        detail: "亀裂は、想像よりずっと下まで続いていた。",
        outcomes: [{ to: "GW_DEEP" }],
      },
      {
        label: "熱に触れる",
        detail: "岩が温かい。地球の内側が、すぐそこにある。",
        outcomes: [{ to: "HOT_SPRING" }],
      },
    ],
  },
  {
    id: "GW_AQUIFER",
    name: "帯水層",
    place: "地下 120m",
    biome: "underground",
    phase: "liquid",
    scene: "aquifer",
    lines: [
      "地上のことは、なにもわからない。",
      "季節も、昼も夜もない。ただ、確実に動いている。",
      "地下の水は止まっていない。ただ、人間より、はるかに遅いだけだ。",
    ],
    hours: [YEAR * 12, YEAR * 400],
    km: [0.5, 20],
    depth: 120,
    temperature: 15,
    tags: ["groundwater"],
    codex: "aquifer",
    timeflow: true,
    choices: [
      {
        label: "上へ押し上げられる",
        detail: "圧力がかかっている。出口さえあれば、水は自分で噴き上がる。",
        outcomes: [{ to: "SPRING", weight: 2 }, { to: "WELL" }],
      },
      {
        label: "さらに深い層へ",
        detail: "下の層の水は、もっと古い。",
        outcomes: [{ to: "GW_DEEP" }],
      },
      {
        label: "井戸に汲み上げられる",
        detail: "真上から、金属の管が降りてきた。",
        outcomes: [{ to: "WELL" }],
        when: exceptRegion("antarctic", "arctic", "pacific"),
      },
    ],
  },
  {
    id: "GW_URBAN",
    name: "街の下の地下水",
    place: "市街地・地下 25m",
    biome: "underground",
    phase: "liquid",
    scene: "aquifer",
    lines: [
      "基礎杭が、地下水の中に何本も突き刺さっている。",
      "地下鉄のトンネルが、すぐ横を通っている。",
    ],
    hours: [YEAR, YEAR * 90],
    km: [0.2, 5],
    depth: 25,
    temperature: 17,
    tags: ["groundwater", "city"],
    timeflow: true,
    choices: [
      {
        label: "トンネルに湧き出す",
        detail: "壁の継ぎ目から染み出し、排水ポンプに集められる。",
        outcomes: [{ to: "CITY_SEWER", weight: 2 }, { to: "SEWAGE_PLANT" }],
      },
      {
        label: "深層へ潜る",
        detail: "街の営みは、地下100mまでは届かない。",
        outcomes: [{ to: "GW_DEEP", weight: 2 }, { to: "GW_AQUIFER" }],
      },
      {
        label: "井戸へ",
        detail: "非常用の井戸が、まだ生きている。",
        outcomes: [{ to: "WELL" }],
      },
    ],
  },
  {
    id: "GW_DEEP",
    name: "深層地下水",
    place: "地下 700m",
    biome: "underground",
    phase: "liquid",
    scene: "deeprock",
    lines: [
      "岩に囲まれ、ほとんど動かない。",
      "この深さの水が最後に空を見たのは、人間が文字を持つ前だ。",
    ],
    hours: [YEAR * 400, YEAR * 30000],
    km: [0.2, 30],
    depth: 700,
    temperature: 28,
    tags: ["groundwater", "deepwater"],
    codex: "deepgw",
    timeflow: true,
    choices: [
      {
        label: "断層に沿って上がる",
        detail: "地面の割れ目が、地下深くと地表をつないでいる。",
        outcomes: [{ to: "HOT_SPRING", weight: 2 }, { to: "SPRING" }],
      },
      {
        label: "深井戸に汲まれる",
        detail: "何百mもの管が、この層まで降りてきた。",
        outcomes: [{ to: "WELL" }],
        when: exceptRegion("antarctic", "arctic", "pacific"),
      },
      {
        label: "留まり続ける",
        detail: "地上では、いくつもの時代が過ぎていく。",
        outcomes: [{ to: "GW_DEEP", weight: 1 }, { to: "GW_AQUIFER", weight: 2 }],
      },
    ],
  },
  {
    id: "CAVE",
    name: "鍾乳洞",
    place: "地下・石灰岩洞",
    biome: "underground",
    phase: "liquid",
    scene: "cave",
    lines: [
      "岩を溶かしながら進むうちに、道が部屋になった。",
      "天井から下がる石も、床から伸びる石も、水が作ったものだ。",
      "一滴が落ちるたび、0.01mmだけ、鍾乳石が伸びる。",
    ],
    hours: [YEAR, YEAR * 900],
    km: [0.1, 8],
    depth: 90,
    temperature: 13,
    tags: ["groundwater", "cave"],
    codex: "cave",
    timeflow: true,
    choices: [
      {
        label: "鍾乳石になる",
        detail: "水は落ちていき、あなたが運んだ石灰だけが残る。",
        outcomes: [{ to: "CAVE_DRIP" }],
      },
      {
        label: "地底湖へ落ちる",
        detail: "暗闇の底に、動かない水面がある。",
        outcomes: [{ to: "CAVE_LAKE" }],
      },
      {
        label: "洞口から出る",
        detail: "遠くに、白い光の穴が見える。",
        outcomes: [{ to: "SPRING" }],
      },
    ],
  },
  {
    id: "CAVE_DRIP",
    name: "鍾乳石のしずく",
    place: "地下・石灰岩洞",
    biome: "underground",
    phase: "liquid",
    scene: "cave",
    lines: [
      "石の先端で、ゆっくり大きくなっていく。",
      "落ちるまで、ときどき何時間もかかる。",
    ],
    hours: [DAY, DAY * 300],
    km: [0, 0.05],
    depth: 85,
    temperature: 13,
    tags: ["cave", "groundwater"],
    choices: [
      {
        label: "落ちる",
        detail: "暗闇に、水の音がひとつ響いた。",
        outcomes: [{ to: "CAVE_LAKE", weight: 2 }, { to: "CAVE" }],
      },
      {
        label: "洞内の空気に溶ける",
        detail: "洞窟の中は、いつも湿度100%に近い。",
        outcomes: [{ to: "MIST" }],
      },
    ],
  },
  {
    id: "CAVE_LAKE",
    name: "地底湖",
    place: "地下・地底湖",
    biome: "underground",
    phase: "liquid",
    scene: "lakedeep",
    lines: [
      "完全な暗闇。完全な静けさ。",
      "水面は、何十年も揺れたことがないように見える。",
    ],
    hours: [YEAR * 2, YEAR * 600],
    km: [0, 4],
    depth: 110,
    temperature: 12,
    tags: ["cave", "groundwater"],
    timeflow: true,
    choices: [
      {
        label: "水路から流れ出す",
        detail: "湖の底に、外へ続く暗い管がある。",
        outcomes: [{ to: "SPRING", weight: 2 }, { to: "GW_FISSURE" }],
      },
      {
        label: "留まる",
        detail: "ここには、季節がない。",
        outcomes: [{ to: "CAVE_LAKE", weight: 1 }, { to: "GW_DEEP", weight: 2 }],
      },
    ],
  },
  {
    id: "HOT_SPRING",
    name: "温泉",
    place: "地下・熱水帯",
    biome: "underground",
    phase: "liquid",
    scene: "hotspring",
    lines: [
      "熱い。岩から溶け出した成分で、体が重くなっている。",
      "地球の内側の熱が、あなたを押し上げていく。",
    ],
    hours: [DAY * 10, YEAR * 40],
    km: [0.2, 8],
    depth: 400,
    temperature: 78,
    tags: ["groundwater", "hotspring"],
    codex: "hotspring",
    choices: [
      {
        label: "地表へ噴き出す",
        detail: "白い湯気の柱が、山肌に立っている。",
        outcomes: [{ to: "HOT_SPRING_BATH", weight: 2 }, { to: "MTN_STREAM" }],
      },
      {
        label: "湯気になって出る",
        detail: "液体のまま地上に着けないほど、熱い。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "HOT_SPRING_BATH",
    name: "露天風呂",
    place: "温泉地",
    biome: "human",
    phase: "liquid",
    scene: "bath",
    lines: [
      "何千年も地下にいた水が、人間の肩を温めている。",
      "湯気の向こうに、雪をかぶった山が見える。",
    ],
    hours: [1, DAY * 3],
    km: [0, 0.5],
    temperature: 42,
    tags: ["human", "hotspring"],
    codex: "bath",
    choices: [
      {
        label: "湯気になる",
        detail: "冷たい空気に触れた瞬間、白くなって立ちのぼる。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "排湯されて川へ",
        detail: "湯船から溢れた湯が、溝を伝って沢へ落ちていく。",
        outcomes: [{ to: "MTN_STREAM", weight: 2 }, { to: "RIVER_MAIN" }],
      },
    ],
  },
  {
    id: "SPRING",
    name: "湧水",
    place: "山麓・湧水地",
    biome: "underground",
    phase: "liquid",
    scene: "spring",
    lines: [
      "何十年ぶりの、光。",
      "苔むした岩のあいだから、押し出されるように地表へ出た。",
      "水温は、一年じゅう変わらない。",
    ],
    hours: [0.5, 40],
    km: [0.01, 2],
    altitude: 400,
    depth: 0,
    temperature: 13,
    tags: ["spring", "groundwater"],
    codex: "spring",
    choices: [
      {
        label: "沢になって流れ出す",
        detail: "湧いたそばから、もう流れになっている。",
        outcomes: [{ to: "MTN_STREAM", weight: 2 }, { to: "BROOK" }],
      },
      {
        label: "人に汲まれる",
        detail: "柄杓が、水面を割った。",
        outcomes: [{ to: "CUP", weight: 2 }, { to: "BOTTLE" }],
        when: exceptRegion("antarctic", "arctic"),
      },
      {
        label: "湿地に広がる",
        detail: "傾きのない土地では、水は流れずに溜まっていく。",
        outcomes: [{ to: "WETLAND" }],
      },
    ],
  },
  {
    id: "WELL",
    name: "井戸",
    place: "地下・揚水管",
    biome: "human",
    phase: "liquid",
    scene: "well",
    lines: [
      "急に、一方向へ強く引かれた。",
      "何十年もかけて下ってきた距離を、数秒で引き戻される。",
    ],
    hours: [0.05, DAY * 5],
    km: [0.05, 0.7],
    depth: 0,
    temperature: 15,
    tags: ["human", "groundwater"],
    codex: "well",
    choices: [
      {
        label: "浄水設備へ送られる",
        detail: "汲み上げられた水は、そのままでは配れない。",
        outcomes: [{ to: "WATERWORKS" }],
      },
      {
        label: "畑に撒かれる",
        detail: "スプリンクラーが、水を空へ投げ上げる。",
        outcomes: [{ to: "PLAIN_SOIL", weight: 2 }, { to: "VAPOR_RISE" }],
      },
      {
        label: "そのまま飲まれる",
        detail: "手押しポンプ。金属の匂いと、冷たさ。",
        outcomes: [{ to: "CUP" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 川
  {
    id: "BROOK",
    name: "小川",
    place: "山あい・小川",
    biome: "river",
    phase: "liquid",
    scene: "stream",
    lines: [
      "石を避け、渦を作り、また合わさる。",
      "さっきまで、あなたは一滴だった。今は、流れの一部だ。",
    ],
    hours: [2, 200],
    km: [1, 25],
    altitude: 500,
    temperature: 11,
    tags: ["stream", "river"],
    codex: "stream",
    choices: [
      {
        label: "支流へ入る",
        detail: "向こうから、もっと大きな流れが来ている。",
        outcomes: [{ to: "TRIBUTARY" }],
      },
      {
        label: "淵に留まる",
        detail: "深く、暗く、流れの止まった場所。魚がいる。",
        outcomes: [{ to: "RIVER_POOL" }],
      },
      {
        label: "河原の石の下へ",
        detail: "川底の砂利の中にも、川は流れている。",
        outcomes: [{ to: "GW_GRAVEL" }],
      },
    ],
  },
  {
    id: "RIVER_POOL",
    name: "淵",
    place: "渓流・淵",
    biome: "river",
    phase: "liquid",
    scene: "rapids",
    lines: [
      "流れが急に緩む。深い緑色の水。",
      "岩陰から、魚がこちらを見ている。",
    ],
    hours: [1, DAY * 30],
    km: [0, 0.5],
    altitude: 480,
    temperature: 12,
    tags: ["river"],
    choices: [
      {
        label: "魚に飲まれる",
        detail: "口が開き、水ごと吸い込まれた。",
        outcomes: [{ to: "FISH_GILL" }],
      },
      {
        label: "また流れに出る",
        detail: "増水。淵の水が、押し出されていく。",
        outcomes: [{ to: "TRIBUTARY", weight: 2 }, { to: "RAPIDS" }],
      },
      {
        label: "底の砂に沈む",
        detail: "川底の砂利の隙間へ、ゆっくり降りていく。",
        outcomes: [{ to: "GW_GRAVEL" }],
      },
    ],
  },
  {
    id: "RAPIDS",
    name: "早瀬",
    place: "渓流・岩場",
    biome: "river",
    phase: "liquid",
    scene: "rapids",
    lines: [
      "岩に叩きつけられ、白く砕け、また集まる。",
      "空気を巻き込んで、水そのものが泡になっている。",
    ],
    hours: [0.1, 6],
    km: [0.5, 8],
    altitude: 420,
    temperature: 11,
    tags: ["river", "stream"],
    codex: "rapids",
    choices: [
      {
        label: "飛沫になって飛ぶ",
        detail: "岩に当たった衝撃で、空中に投げ出される。",
        outcomes: [{ to: "VAPOR_RISE", weight: 2 }, { to: "MTN_MOSS" }],
      },
      {
        label: "そのまま下る",
        detail: "止まる理由が、どこにもない。",
        outcomes: [{ to: "TRIBUTARY", weight: 2 }, { to: "WATERFALL" }],
      },
    ],
  },
  {
    id: "WATERFALL",
    name: "滝",
    place: "渓谷・滝",
    biome: "river",
    phase: "liquid",
    scene: "waterfall",
    lines: [
      "足元が、消えた。",
      "落ちながら、水は水でいられなくなる。ばらばらの粒になる。",
      "下から、地響きのような音が上がってくる。",
    ],
    hours: [0.01, 0.2],
    km: [0.02, 0.2],
    altitude: 320,
    temperature: 11,
    tags: ["river"],
    codex: "waterfall",
    choices: [
      {
        label: "滝壺へ叩き込まれる",
        detail: "深く沈み、渦に巻かれ、しばらく浮上できない。",
        outcomes: [{ to: "RIVER_POOL", weight: 2 }, { to: "TRIBUTARY" }],
      },
      {
        label: "水煙になる",
        detail: "滝のまわりだけ、いつも雨が降っているように見える。",
        outcomes: [{ to: "MIST", weight: 2 }, { to: "MTN_MOSS" }],
      },
    ],
  },
  {
    id: "TRIBUTARY",
    name: "支流",
    place: "上流域",
    biome: "river",
    phase: "liquid",
    scene: "river",
    lines: [
      "幅が広がった。流れが、少し重くなった。",
      "いくつもの沢が、ここで一本になっている。",
    ],
    hours: [2, 200],
    km: [3, 60],
    altitude: 200,
    temperature: 13,
    tags: ["river"],
    codex: "river",
    choices: [
      {
        label: "本流へ出る",
        detail: "合流点。水の色が、はっきり二つに分かれている。",
        outcomes: [{ to: "RIVER_MAIN" }],
      },
      {
        label: "ダムに堰き止められる",
        detail: "谷をふさぐ、灰色の壁。",
        outcomes: [{ to: "DAM" }],
        when: exceptRegion("antarctic", "arctic"),
      },
      {
        label: "取水口へ吸い込まれる",
        detail: "岸に、格子のはまった四角い口が開いている。",
        outcomes: [{ to: "INTAKE" }],
        when: exceptRegion("antarctic", "arctic"),
      },
    ],
  },
  {
    id: "RIVER_MAIN",
    name: "川",
    place: "中流域",
    biome: "river",
    phase: "liquid",
    scene: "river",
    lines: [
      "両岸が、遠い。",
      "橋が、頭上を通り過ぎていく。",
      "この水の何割かは、雨ではなく、地下から湧いた水だ。",
    ],
    hours: [4, 300],
    km: [10, 120],
    altitude: 60,
    temperature: 16,
    tags: ["river"],
    codex: "river",
    choices: [
      {
        label: "本流の中心へ",
        detail: "いちばん速い流れは、川の真ん中の少し下にある。",
        outcomes: [{ to: "GREAT_RIVER" }],
      },
      {
        label: "岸辺の湿地へ",
        detail: "葦の茂る、流れの緩い場所。",
        outcomes: [{ to: "WETLAND" }],
      },
      {
        label: "浄水場の取水口へ",
        detail: "この街の水道は、ここから始まっている。",
        outcomes: [{ to: "INTAKE" }],
        when: exceptRegion("antarctic", "arctic"),
      },
    ],
  },
  {
    id: "GREAT_RIVER",
    name: "大河",
    place: "下流域",
    biome: "river",
    phase: "liquid",
    scene: "greatriver",
    lines: [
      "対岸が、霞んで見えない。",
      "上流のすべての雨、すべての雪、すべての湧水が、ここにいる。",
      "その巨大な流れを構成している、一滴。それがあなたです。",
    ],
    hours: [10, 400],
    km: [30, 400],
    altitude: 15,
    temperature: 18,
    tags: ["river", "greatriver"],
    codex: "greatriver",
    choices: [
      {
        label: "河口へ向かう",
        detail: "水が、少しずつ塩辛くなってくる。",
        outcomes: [{ to: "ESTUARY" }],
      },
      {
        label: "洪水で溢れる",
        detail: "上流で、記録的な雨が降ったらしい。",
        outcomes: [{ to: "FLOOD" }],
      },
      {
        label: "川底へ沈む",
        detail: "重い水は、下を流れる。砂の中へ潜っていく。",
        outcomes: [{ to: "GW_GRAVEL", weight: 2 }, { to: "WETLAND" }],
      },
    ],
  },
  {
    id: "FLOOD",
    name: "洪水",
    place: "氾濫原",
    biome: "river",
    phase: "liquid",
    scene: "flood",
    lines: [
      "堤防を越えた。",
      "水は、本来ここにいてよかった。人間が来る前は、ここも川だった。",
    ],
    hours: [DAY, DAY * 20],
    km: [1, 30],
    altitude: 12,
    temperature: 19,
    tags: ["river", "flood"],
    codex: "flood",
    choices: [
      {
        label: "田畑に染み込む",
        detail: "泥と一緒に、上流の栄養が運ばれてきた。",
        outcomes: [{ to: "PLAIN_SOIL", weight: 2 }, { to: "PADDY" }],
      },
      {
        label: "川へ戻る",
        detail: "水位が下がる。水は、また低いほうへ集まっていく。",
        outcomes: [{ to: "GREAT_RIVER" }],
      },
      {
        label: "溜まって残る",
        detail: "引かなかった水が、新しい池になった。",
        outcomes: [{ to: "WETLAND", weight: 2 }, { to: "POND" }],
      },
    ],
  },
  {
    id: "WETLAND",
    name: "湿地",
    place: "河畔・湿原",
    biome: "river",
    phase: "liquid",
    scene: "wetland",
    lines: [
      "流れているのか、止まっているのか、わからない。",
      "葦の根と、泥と、無数の小さな生きもののあいだ。",
    ],
    hours: [DAY * 3, YEAR * 5],
    km: [0.1, 6],
    altitude: 10,
    temperature: 17,
    tags: ["wetland", "river"],
    codex: "wetland",
    timeflow: true,
    choices: [
      {
        label: "泥炭に閉じ込められる",
        detail: "分解されない植物が、何mも積み重なっている。",
        outcomes: [{ to: "PEAT" }],
      },
      {
        label: "植物に吸われる",
        detail: "葦が、ここの水を空へ送り返している。",
        outcomes: [{ to: "CROP_ROOT", weight: 2 }, { to: "TREE_STOMA" }],
      },
      {
        label: "また川へ出る",
        detail: "湿地は、水をゆっくり川へ返す装置でもある。",
        outcomes: [{ to: "RIVER_MAIN", weight: 2 }, { to: "ESTUARY" }],
      },
    ],
  },
  {
    id: "PEAT",
    name: "泥炭",
    place: "湿原・泥炭層",
    biome: "underground",
    phase: "liquid",
    scene: "wetland",
    lines: [
      "酸素がなく、冷たく、酸性。",
      "ここでは、落ちた植物が何千年も腐らずに残る。",
    ],
    hours: [YEAR * 30, YEAR * 6000],
    km: [0, 1],
    depth: 3,
    temperature: 8,
    tags: ["wetland", "groundwater"],
    codex: "peat",
    timeflow: true,
    choices: [
      {
        label: "掘り出される",
        detail: "スコップが、上の層を割った。何千年ぶりかの光。",
        outcomes: [{ to: "VAPOR_RISE", weight: 2 }, { to: "RIVER_MAIN" }],
      },
      {
        label: "沼へ染み出す",
        detail: "茶色く染まった水が、ゆっくり地表へ戻っていく。",
        outcomes: [{ to: "WETLAND", weight: 2 }, { to: "TUNDRA_POOL" }],
      },
    ],
  },
  {
    id: "ESTUARY",
    name: "河口",
    place: "河口・汽水域",
    biome: "river",
    phase: "liquid",
    scene: "estuary",
    lines: [
      "川の水と、海の水が、層になってすれ違っている。",
      "軽い淡水が上を、重い海水が下を。あなたは、その境目にいる。",
    ],
    hours: [DAY, DAY * 60],
    km: [1, 25],
    altitude: 0,
    salinity: "brackish",
    temperature: 19,
    tags: ["estuary", "river"],
    codex: "estuary",
    choices: [
      {
        label: "外洋へ押し出される",
        detail: "引き潮。川が、海へ向かって伸びていく。",
        outcomes: [{ to: "OCEAN_COAST", weight: 2 }, { to: "OCEAN_SURFACE" }],
      },
      {
        label: "干潟へ残される",
        detail: "潮が引いて、泥の平原が現れた。無数の穴が開いている。",
        outcomes: [{ to: "TIDAL_FLAT" }],
      },
      {
        label: "満ち潮で川を遡る",
        detail: "海水が、川を逆流していく。",
        outcomes: [{ to: "RIVER_MAIN" }],
      },
    ],
  },
  {
    id: "TIDAL_FLAT",
    name: "干潟",
    place: "河口・干潟",
    biome: "ocean",
    phase: "liquid",
    scene: "estuary",
    lines: [
      "泥の粒のあいだに、閉じ込められている。",
      "貝が水を吸い、吐き出す。この泥全体が、巨大な濾過装置だ。",
    ],
    hours: [3, DAY * 20],
    km: [0, 3],
    salinity: "brackish",
    temperature: 21,
    tags: ["estuary", "life"],
    codex: "tidalflat",
    choices: [
      {
        label: "貝の中を通る",
        detail: "殻の隙間から吸い込まれ、鰓を抜けて、また出ていく。",
        outcomes: [{ to: "SHELLFISH" }],
      },
      {
        label: "満ち潮に連れ戻される",
        detail: "遠くから、水の縁が近づいてくる。",
        outcomes: [{ to: "OCEAN_COAST" }],
      },
      {
        label: "日射で蒸発する",
        detail: "干潟の泥が乾いて、白い塩が浮いてきた。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "DAM",
    name: "ダム湖",
    place: "上流域・ダム",
    biome: "human",
    phase: "liquid",
    scene: "dam",
    lines: [
      "流れが、突然なくなった。",
      "谷ひとつが、まるごと水に沈んでいる。",
      "人間は、水の時間を止めることができる。しばらくのあいだは。",
    ],
    hours: [DAY * 10, YEAR * 6],
    km: [0.5, 15],
    altitude: 300,
    depth: 40,
    temperature: 12,
    tags: ["dam", "human", "lake"],
    codex: "dam",
    timeflow: true,
    choices: [
      {
        label: "発電機を通る",
        detail: "細い管に吸い込まれ、羽根を回して、また川へ。",
        outcomes: [{ to: "RIVER_MAIN", weight: 2 }, { to: "TRIBUTARY" }],
      },
      {
        label: "水道へ引かれる",
        detail: "この湖は、下流の街の蛇口とつながっている。",
        outcomes: [{ to: "WATERWORKS" }],
      },
      {
        label: "湖底に沈む",
        detail: "深いところの水は、何年も入れ替わらない。",
        outcomes: [{ to: "LAKE_DEEP" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 湖
  {
    id: "LAKE_SURFACE",
    name: "湖面",
    place: "湖・表層",
    biome: "lake",
    phase: "liquid",
    scene: "lake",
    lines: [
      "波紋が、静かに外へ広がっていく。",
      "空と、山と、雲。全部が、下向きにもう一つある。",
    ],
    hours: [DAY, YEAR * 3],
    km: [0.1, 12],
    altitude: 700,
    temperature: 15,
    tags: ["lake"],
    codex: "lake",
    choices: [
      {
        label: "蒸発する",
        detail: "湖は、雨で受け取った水の多くを、そのまま空へ返している。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "深く沈む",
        detail: "冬。表層が冷えて重くなり、湖全体が入れ替わる。",
        outcomes: [{ to: "LAKE_DEEP" }],
      },
      {
        label: "流出口へ",
        detail: "湖の水は、一か所だけ、外へ出ることを許されている。",
        outcomes: [{ to: "RIVER_MAIN", weight: 2 }, { to: "TRIBUTARY" }],
      },
    ],
  },
  {
    id: "LAKE_DEEP",
    name: "湖の底",
    place: "湖・深層",
    biome: "lake",
    phase: "liquid",
    scene: "lakedeep",
    lines: [
      "光が届かない。水温は、一年じゅう4℃で変わらない。",
      "上の層とは、ほとんど混ざらない。別の世界のようだ。",
    ],
    hours: [YEAR, YEAR * 200],
    km: [0, 3],
    depth: 90,
    temperature: 4,
    tags: ["lake", "deepwater"],
    codex: "lakedeep",
    timeflow: true,
    choices: [
      {
        label: "湧昇に乗って上がる",
        detail: "季節が変わり、深いところの水が持ち上げられる。",
        outcomes: [{ to: "LAKE_SURFACE" }],
      },
      {
        label: "湖底から地下へ",
        detail: "湖の底にも、水が抜けていく道がある。",
        outcomes: [{ to: "GW_AQUIFER", weight: 2 }, { to: "SPRING" }],
      },
      {
        label: "プランクトンに取り込まれる",
        detail: "小さすぎて見えない生きものが、水そのものを体にしている。",
        outcomes: [{ to: "PLANKTON" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 人間社会
  {
    id: "INTAKE",
    name: "取水口",
    place: "河川・取水堰",
    biome: "human",
    phase: "liquid",
    scene: "waterworks",
    lines: [
      "自然だけだった世界に、突然、直線が現れる。",
      "格子。ゲート。コンクリート。",
      "ここから先の行き先は、もう、水が決めるのではない。",
    ],
    hours: [0.2, 24],
    km: [0.2, 8],
    temperature: 16,
    tags: ["human"],
    codex: "intake",
    choices: [
      {
        label: "導水管へ入る",
        detail: "太く、暗く、まっすぐな管。",
        outcomes: [{ to: "WATERWORKS" }],
      },
      {
        label: "格子で弾かれる",
        detail: "ゴミと一緒に押し戻され、また川へ。",
        outcomes: [{ to: "RIVER_MAIN" }],
      },
      {
        label: "工業用に分けられる",
        detail: "別の管が、街とは違う方向へ伸びている。",
        outcomes: [{ to: "FACTORY" }],
      },
    ],
  },
  {
    id: "WATERWORKS",
    name: "浄水場",
    place: "浄水場",
    biome: "human",
    phase: "liquid",
    scene: "waterworks",
    lines: [
      "薬品が入れられ、濁りが集まって、沈んでいく。",
      "砂の層をくぐらされる。地下水になったときと、少し似ている。",
      "出てきたときには、透明になっていた。",
    ],
    hours: [3, 40],
    km: [0.1, 2],
    temperature: 17,
    tags: ["human"],
    codex: "waterworks",
    choices: [
      {
        label: "配水池から送り出される",
        detail: "高いところの池に上げられ、あとは重力で街へ配られる。",
        outcomes: [{ to: "PIPE" }],
      },
      {
        label: "沈殿池の泥と一緒に",
        detail: "濁りとして分けられた水は、別の道をたどる。",
        outcomes: [{ to: "SEWAGE_PLANT" }],
      },
    ],
  },
  {
    id: "PIPE",
    name: "水道管",
    place: "地下・配水管",
    biome: "human",
    phase: "liquid",
    scene: "pipe",
    lines: [
      "街の下に、水の道が張りめぐらされている。",
      "総延長は、地球を何周もするほど。",
      "圧力がかかっていて、止まることが許されない。",
    ],
    hours: [1, 200],
    km: [0.5, 30],
    depth: 1.5,
    temperature: 16,
    tags: ["human", "tap", "city"],
    codex: "pipe",
    choices: [
      {
        label: "建物へ分岐する",
        detail: "細い枝管が、一軒ずつに向かって伸びている。",
        outcomes: [{ to: "TAP" }],
      },
      {
        label: "漏水として地中へ",
        detail: "古い継ぎ目から、じわじわと外へ。",
        outcomes: [{ to: "GW_URBAN" }],
      },
      {
        label: "ボトルに詰められる",
        detail: "工場のラインで、次々と蓋が閉められていく。",
        outcomes: [{ to: "BOTTLE" }],
      },
    ],
  },
  {
    id: "TAP",
    name: "蛇口",
    place: "住宅・給水栓",
    biome: "human",
    phase: "liquid",
    scene: "faucet",
    lines: [
      "レバーが持ち上がる音。",
      "圧力から解放されて、空気の中へ落ちていく。",
      "何十年も地下にいた水が、いま、誰かの手のひらの上にいる。",
    ],
    hours: [0.01, 0.5],
    km: [0, 0.02],
    temperature: 18,
    tags: ["human", "tap"],
    codex: "tap",
    choices: [
      {
        label: "コップへ",
        detail: "ガラスの壁に囲まれて、水面が静かになる。",
        outcomes: [{ to: "CUP" }],
      },
      {
        label: "シャワーへ",
        detail: "細かい穴を通って、無数の粒に分かれる。",
        outcomes: [{ to: "SHOWER" }],
      },
      {
        label: "洗濯機へ",
        detail: "回る。ものすごい速さで、ずっと回っている。",
        outcomes: [{ to: "WASHER" }],
      },
    ],
  },
  {
    id: "CUP",
    name: "コップの中",
    place: "台所",
    biome: "human",
    phase: "liquid",
    scene: "cup",
    lines: [
      "波が止まり、水面が完全に平らになった。",
      "外の光が、コップの底に丸い模様を作っている。",
      "上から、影が近づいてくる。",
    ],
    hours: [0.05, 12],
    km: [0, 0.01],
    temperature: 19,
    tags: ["human", "tap"],
    codex: "cup",
    choices: [
      {
        label: "飲まれる",
        detail: "傾く。ガラスの縁を越える。",
        outcomes: [{ to: "HUMAN_BODY" }],
      },
      {
        label: "置きっぱなしにされる",
        detail: "一日たつと、水面が少しだけ下がっていた。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "流しに捨てられる",
        detail: "排水口の渦に、まっすぐ引き込まれる。",
        outcomes: [{ to: "CITY_SEWER" }],
      },
    ],
  },
  {
    id: "BOTTLE",
    name: "ペットボトル",
    place: "工場 → 店 → 誰かの鞄",
    biome: "human",
    phase: "liquid",
    scene: "cup",
    lines: [
      "透明な壁に、ぴったり閉じ込められた。",
      "トラック、倉庫、冷蔵棚。水が、商品として運ばれていく。",
      "地下で何百年か過ごしたあと、こういう場所に来ることもある。",
    ],
    hours: [DAY * 3, DAY * 400],
    km: [10, 900],
    temperature: 12,
    tags: ["human", "tap"],
    codex: "bottle",
    timeflow: true,
    choices: [
      {
        label: "誰かに飲まれる",
        detail: "蓋が開く音。空気が入り込む。",
        outcomes: [{ to: "HUMAN_BODY" }],
      },
      {
        label: "捨てられる",
        detail: "中身が半分残ったまま、蓋を閉められて。",
        outcomes: [{ to: "CITY_SEWER", weight: 2 }, { to: "CITY_DRAIN" }],
      },
    ],
  },
  {
    id: "SHOWER",
    name: "シャワー",
    place: "浴室",
    biome: "human",
    phase: "liquid",
    scene: "bath",
    lines: [
      "温められ、細かい穴から撃ち出される。",
      "皮膚に当たって砕け、白い湯気が立ちのぼる。",
    ],
    hours: [0.01, 0.3],
    km: [0, 0.01],
    temperature: 40,
    tags: ["human"],
    codex: "bath",
    choices: [
      {
        label: "排水口へ",
        detail: "泡と一緒に、渦を巻いて消えていく。",
        outcomes: [{ to: "CITY_SEWER" }],
      },
      {
        label: "湯気になる",
        detail: "浴室の天井に集まり、また滴になって落ちてくる。",
        outcomes: [{ to: "VAPOR_RISE", weight: 2 }, { to: "MIST" }],
      },
    ],
  },
  {
    id: "WASHER",
    name: "洗濯機の中",
    place: "住宅・洗濯機",
    biome: "human",
    phase: "liquid",
    scene: "bath",
    lines: [
      "回転。逆回転。また回転。",
      "繊維のあいだを何度も往復させられている。",
    ],
    hours: [0.5, 2],
    km: [0.1, 2],
    temperature: 22,
    tags: ["human"],
    codex: "washer",
    choices: [
      {
        label: "排水される",
        detail: "灰色に濁った水が、一気に押し出される。",
        outcomes: [{ to: "CITY_SEWER" }],
      },
      {
        label: "布に残って干される",
        detail: "ベランダ。風。よく晴れた日。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "FACTORY",
    name: "工場",
    place: "工業地帯",
    biome: "human",
    phase: "liquid",
    scene: "factory",
    lines: [
      "冷やすために使われる。洗うために使われる。",
      "水は、ほとんどあらゆる物の製造工程を通っている。",
    ],
    hours: [1, DAY * 30],
    km: [0.1, 5],
    temperature: 45,
    tags: ["human", "factory"],
    codex: "factory",
    choices: [
      {
        label: "冷却塔から蒸発する",
        detail: "白い湯気の柱が、屋上から立ちのぼっている。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "処理されて放流される",
        detail: "工場の中にも、水をきれいにする設備がある。",
        outcomes: [{ to: "SEWAGE_PLANT", weight: 2 }, { to: "RIVER_MAIN" }],
      },
      {
        label: "製品の中に残る",
        detail: "飲みものに、紙に、コンクリートに。水はそこにいる。",
        outcomes: [{ to: "BOTTLE", weight: 2 }, { to: "HUMAN_BODY" }],
      },
    ],
  },
  {
    id: "CITY_SEWER",
    name: "下水管",
    place: "地下・下水道",
    biome: "human",
    phase: "liquid",
    scene: "sewer",
    lines: [
      "暗い。温かい。街じゅうの生活が、ここで一本になる。",
      "誰かの風呂の湯と、誰かの洗い物と、あなた。",
    ],
    hours: [0.2, 12],
    km: [0.5, 20],
    depth: 6,
    temperature: 21,
    tags: ["human", "sewage", "city"],
    codex: "sewer",
    choices: [
      {
        label: "処理場へ運ばれる",
        detail: "管はすべて、街の端の大きな施設へ向かっている。",
        outcomes: [{ to: "SEWAGE_PLANT" }],
      },
      {
        label: "大雨で溢れる",
        detail: "処理能力を超えた水が、そのまま川へ吐き出される。",
        outcomes: [{ to: "RIVER_MAIN", weight: 2 }, { to: "ESTUARY" }],
      },
    ],
  },
  {
    id: "SEWAGE_PLANT",
    name: "下水処理場",
    place: "下水処理場",
    biome: "human",
    phase: "liquid",
    scene: "waterworks",
    lines: [
      "巨大な四角い池が、いくつも並んでいる。",
      "空気を送り込まれ、微生物に汚れを食べさせる。",
      "この水は、人間の暮らしを通り抜けて、また自然へ戻ろうとしている。",
    ],
    hours: [8, 60],
    km: [0.1, 2],
    temperature: 20,
    tags: ["human", "sewage"],
    codex: "sewageplant",
    choices: [
      {
        label: "川へ放流される",
        detail: "きれいになった水が、放流渠から静かに出ていく。",
        outcomes: [{ to: "RIVER_MAIN", weight: 2 }, { to: "GREAT_RIVER" }],
      },
      {
        label: "海へ放流される",
        detail: "長い管が、沖まで伸びている。",
        outcomes: [{ to: "OCEAN_COAST" }],
      },
      {
        label: "再生水として使われる",
        detail: "トイレの洗浄水、街路の散水、川の維持用水へ。",
        outcomes: [{ to: "CITY_PARK", weight: 2 }, { to: "PIPE" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 生きもの
  {
    id: "HUMAN_BODY",
    name: "人間の体の中",
    place: "体内",
    biome: "life",
    phase: "liquid",
    scene: "body",
    lines: [
      "喉を落ち、暗く、温かい場所へ。",
      "壁が動いている。この人の体の60%は、あなたと同じ水だ。",
      "しばらくのあいだ、あなたは「この人」の一部になる。",
    ],
    hours: [2, DAY * 12],
    km: [0.1, 60],
    temperature: 37,
    tags: ["human", "body", "life"],
    codex: "humanbody",
    choices: [
      {
        label: "汗になる",
        detail: "皮膚の穴から押し出され、体の熱を持って蒸発する。",
        outcomes: [{ to: "HUMAN_SWEAT" }],
      },
      {
        label: "息に混じる",
        detail: "肺の奥まで運ばれ、吐く息の白さになる。",
        outcomes: [{ to: "HUMAN_BREATH" }],
      },
      {
        label: "体の外へ出される",
        detail: "腎臓で選り分けられ、下水へ向かう。",
        outcomes: [{ to: "CITY_SEWER" }],
      },
    ],
  },
  {
    id: "HUMAN_SWEAT",
    name: "汗",
    place: "皮膚の上",
    biome: "life",
    phase: "liquid",
    scene: "body",
    lines: [
      "体の表面に押し出された。",
      "蒸発するとき、あなたはこの人から熱を奪っていく。",
      "そのために、汗はある。",
    ],
    hours: [0.05, 2],
    km: [0, 0.01],
    temperature: 34,
    tags: ["body", "life"],
    choices: [
      {
        label: "蒸発する",
        detail: "皮膚が、少し涼しくなった。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "拭われる",
        detail: "タオルの繊維に吸い込まれる。",
        outcomes: [{ to: "WASHER", weight: 2 }, { to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "HUMAN_BREATH",
    name: "呼気",
    place: "口元",
    biome: "life",
    phase: "gas",
    scene: "vapor",
    lines: [
      "肺の奥、無数の小さな袋の壁から、空気に混ざった。",
      "外に出た瞬間、白くなる。冬だ。",
      "人はひと息ごとに、体の水をすこしずつ空へ返している。",
    ],
    hours: [0.01, 0.5],
    km: [0, 0.05],
    temperature: 34,
    tags: ["body", "life", "vapor"],
    codex: "breath",
    choices: [
      {
        label: "空へのぼる",
        detail: "白い塊が、ほどけて見えなくなる。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "窓に結露する",
        detail: "冷たいガラスに触れて、また液体に戻った。",
        outcomes: [{ to: "CITY_PUDDLE", weight: 2 }, { to: "CITY_SEWER" }],
      },
    ],
  },
  {
    id: "ANIMAL_BODY",
    name: "動物の体の中",
    place: "森・体内",
    biome: "life",
    phase: "liquid",
    scene: "creature",
    lines: [
      "舌に絡め取られ、体温の中へ。",
      "心臓の音が、体じゅうに響いている。",
    ],
    hours: [1, DAY * 6],
    km: [0.5, 60],
    temperature: 38,
    tags: ["animal", "life"],
    codex: "animal",
    choices: [
      {
        label: "運ばれて、外へ出される",
        detail: "森のずっと奥。ここまで、水は自分では来られなかった。",
        outcomes: [{ to: "FOREST_FLOOR", weight: 2 }, { to: "SOIL_SHALLOW" }],
      },
      {
        label: "息に混じって出る",
        detail: "白い呼気が、朝の森に流れていく。",
        outcomes: [{ to: "HUMAN_BREATH" }],
      },
    ],
  },
  {
    id: "FISH_GILL",
    name: "魚のえら",
    place: "水中・体内",
    biome: "life",
    phase: "liquid",
    scene: "creature",
    lines: [
      "口から入り、赤い櫛のような器官のあいだを抜ける。",
      "ここで、水と血が、薄い膜ごしにすれ違っている。",
    ],
    hours: [0.01, DAY * 2],
    km: [0.1, 200],
    temperature: 14,
    tags: ["fish", "life"],
    codex: "fishgill",
    choices: [
      {
        label: "また水へ出る",
        detail: "えた蓋が開き、体の後ろへ押し出される。",
        outcomes: [
          { to: "RIVER_MAIN", weight: 2 },
          { to: "OCEAN_SURFACE" },
          { to: "POND" },
        ],
      },
      {
        label: "魚とともに川を上る",
        detail: "海から生まれた川へ、何百kmも遡っていく。",
        outcomes: [{ to: "TRIBUTARY", weight: 2 }, { to: "RIVER_POOL" }],
      },
      {
        label: "魚とともに海へ下る",
        detail: "水が、だんだん塩辛くなっていく。",
        outcomes: [{ to: "ESTUARY", weight: 2 }, { to: "OCEAN_CURRENT" }],
      },
    ],
  },
  {
    id: "SHELLFISH",
    name: "貝の中",
    place: "干潟・体内",
    biome: "life",
    phase: "liquid",
    scene: "creature",
    lines: [
      "殻の隙間から吸い込まれる。",
      "一日に何百リットルもの水が、この小さな体を通っている。",
    ],
    hours: [0.05, DAY],
    km: [0, 0.5],
    salinity: "brackish",
    temperature: 20,
    tags: ["life", "estuary"],
    choices: [
      {
        label: "吐き出される",
        detail: "入ってきたときより、少しだけ澄んでいる。",
        outcomes: [{ to: "OCEAN_COAST", weight: 2 }, { to: "TIDAL_FLAT" }],
      },
      {
        label: "鳥に食べられる",
        detail: "くちばしが、殻をこじ開けた。",
        outcomes: [{ to: "ANIMAL_BODY" }],
      },
    ],
  },
  {
    id: "PLANKTON",
    name: "プランクトン",
    place: "水中・表層",
    biome: "life",
    phase: "liquid",
    scene: "creature",
    lines: [
      "一ミリの何分の一かの体に、取り込まれた。",
      "この生きものは、あなたと光から、酸素を作っている。",
    ],
    hours: [1, DAY * 20],
    km: [0.1, 40],
    temperature: 16,
    tags: ["life"],
    codex: "plankton",
    choices: [
      {
        label: "食べられて、もっと大きな体へ",
        detail: "食物連鎖の階段を、一段ずつ上がっていく。",
        outcomes: [{ to: "WHALE", weight: 2 }, { to: "FISH_GILL" }],
      },
      {
        label: "分解されて水に戻る",
        detail: "体が壊れ、また、ただの水になる。",
        outcomes: [{ to: "OCEAN_SURFACE", weight: 2 }, { to: "LAKE_SURFACE" }],
      },
      {
        label: "沈んでいく",
        detail: "死んだ体が、雪のように深海へ降りていく。",
        outcomes: [{ to: "OCEAN_DEEP" }],
      },
    ],
  },
  {
    id: "WHALE",
    name: "鯨の体の中",
    place: "外洋・体内",
    biome: "life",
    phase: "liquid",
    scene: "creature",
    lines: [
      "地球でいちばん大きな体の中にいる。",
      "その体も、ほとんどが水でできている。",
      "低い音が、何百kmも先まで届いていくのがわかる。",
    ],
    hours: [DAY, DAY * 40],
    km: [100, 4000],
    salinity: "saline",
    temperature: 36,
    tags: ["life", "ocean"],
    codex: "whale",
    choices: [
      {
        label: "潮とともに噴き上がる",
        detail: "海面。空。白い霧が、高く上がる。",
        outcomes: [{ to: "VAPOR_RISE", weight: 2 }, { to: "OCEAN_SURFACE" }],
      },
      {
        label: "海へ排出される",
        detail: "また、ただの海水に戻る。",
        outcomes: [{ to: "OCEAN_CURRENT", weight: 2 }, { to: "OCEAN_SURFACE" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 海
  {
    id: "OCEAN_COAST",
    name: "沿岸",
    place: "沿岸域",
    biome: "ocean",
    phase: "liquid",
    scene: "coast",
    lines: [
      "波が、寄せては返している。",
      "同じ場所を、何度も何度も行き来させられる。",
    ],
    hours: [DAY, YEAR * 2],
    km: [1, 200],
    salinity: "saline",
    temperature: 19,
    tags: ["ocean"],
    codex: "coast",
    choices: [
      {
        label: "砕けて飛沫になる",
        detail: "波が岩に当たり、細かい粒が風にさらわれていく。",
        outcomes: [{ to: "VAPOR_RISE", weight: 2 }, { to: "SEA_SALT" }],
      },
      {
        label: "沖へ出る",
        detail: "離岸流。岸から引き離す、速い帯。",
        outcomes: [{ to: "OCEAN_SURFACE" }],
      },
      {
        label: "サンゴの海へ",
        detail: "透明度が上がる。色が、急に増える。",
        outcomes: [{ to: "CORAL" }],
        when: inRegion("seasia", "pacific", "amazon"),
      },
    ],
  },
  {
    id: "SEA_SALT",
    name: "海塩粒子",
    place: "海上の大気",
    biome: "sky",
    phase: "gas",
    scene: "vapor",
    lines: [
      "波の泡がはじけて、微小な塩の粒と一緒に空へ飛ばされた。",
      "この粒があるから、雲の中で水滴が育つことができる。",
      "あなたはこれから、次の誰かの雨の、核になる。",
    ],
    hours: [1, DAY * 9],
    km: [10, 3000],
    temperature: 16,
    tags: ["ocean", "vapor", "sky"],
    codex: "seasalt",
    choices: [
      {
        label: "雲の核になる",
        detail: "まわりの水蒸気が、あなたを中心に集まってくる。",
        outcomes: [{ to: "VAPOR_HIGH" }],
      },
      {
        label: "陸へ運ばれる",
        detail: "海風が、内陸へ吹き込んでいる。",
        outcomes: [{ to: "MIST", weight: 2 }, { to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "CORAL",
    name: "サンゴ礁",
    place: "熱帯・浅海",
    biome: "ocean",
    phase: "liquid",
    scene: "coral",
    lines: [
      "光が、水の中まで届いている。",
      "無数の生きものが、水を吸い、吐き、その隙間を魚が抜けていく。",
    ],
    hours: [DAY * 3, YEAR * 4],
    km: [1, 90],
    salinity: "saline",
    temperature: 28,
    depth: 8,
    tags: ["ocean", "coral", "life"],
    codex: "coral",
    choices: [
      {
        label: "サンゴの体を通る",
        detail: "小さな触手が、水ごと餌を捕まえている。",
        outcomes: [{ to: "PLANKTON", weight: 2 }, { to: "FISH_GILL" }],
      },
      {
        label: "礁の外へ出る",
        detail: "急に、海の底が見えなくなった。",
        outcomes: [{ to: "OCEAN_CURRENT", weight: 2 }, { to: "OCEAN_DEEP" }],
      },
      {
        label: "浅瀬で温められる",
        detail: "熱帯の浅い海は、地球でもっとも蒸発が盛んな場所のひとつ。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
    ],
  },
  {
    id: "OCEAN_SURFACE",
    name: "海面",
    place: "外洋・表層",
    biome: "ocean",
    phase: "liquid",
    scene: "oceansurface",
    lines: [
      "画面いっぱいの青。",
      "地球の水の97%が、ここにある。",
      "無数の水の中で、あなただけが、小さく光っている。",
    ],
    hours: [DAY * 5, YEAR * 12],
    km: [10, 900],
    salinity: "saline",
    temperature: 22,
    tags: ["ocean"],
    codex: "opensea",
    timeflow: true,
    choices: [
      {
        label: "蒸発する",
        detail: "地球の空へのぼる水の、ほとんどはここから出ていく。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "海流に乗る",
        detail: "海の中にも川がある。それは大陸を越えて流れている。",
        outcomes: [{ to: "OCEAN_CURRENT" }],
      },
      {
        label: "深く沈む",
        detail: "冷たく、塩辛い水は重い。ゆっくりと落ちていく。",
        outcomes: [{ to: "OCEAN_DEEP" }],
      },
    ],
  },
  {
    id: "OCEAN_CURRENT",
    name: "海流",
    place: "外洋・海流帯",
    biome: "ocean",
    phase: "liquid",
    scene: "oceancurrent",
    lines: [
      "運ばれている。自分では、なにもしていない。",
      "海流は、赤道の熱を極へ運び、地球の気候そのものを作っている。",
      "日本の沖から、太平洋を越えて、別の大陸の岸へ。",
    ],
    hours: [YEAR, YEAR * 40],
    km: [2000, 22000],
    salinity: "saline",
    temperature: 18,
    tags: ["ocean", "current"],
    codex: "current",
    timeflow: true,
    choices: [
      {
        label: "暖流に乗って北へ",
        detail: "水温が、まわりの海より高い。空気が、そこだけ湿る。",
        outcomes: [{ to: "VAPOR_RISE", weight: 2 }, { to: "OCEAN_SURFACE" }],
      },
      {
        label: "寒冷海域へ入る",
        detail: "冷えて、重くなって、沈みはじめる。",
        outcomes: [{ to: "OCEAN_DEEP", weight: 2 }, { to: "SEA_ICE" }],
      },
      {
        label: "もう一つの海へ渡る",
        detail: "海はすべてつながっている。境目は、人間が決めたものだ。",
        outcomes: [{ to: "OCEAN_CURRENT", weight: 1 }, { to: "OCEAN_COAST", weight: 2 }],
      },
    ],
  },
  {
    id: "OCEAN_DEEP",
    name: "深海",
    place: "外洋・深度 3,900m",
    biome: "ocean",
    phase: "liquid",
    scene: "oceandeep",
    lines: [
      "光は、まったくない。",
      "水温2℃。圧力は、地上の400倍。",
      "この深さの水が最後に空気に触れたのは、千年前のことだ。",
    ],
    hours: [YEAR * 200, YEAR * 2000],
    km: [500, 14000],
    salinity: "saline",
    depth: 3900,
    temperature: 2,
    tags: ["ocean", "abyss", "deepwater"],
    codex: "abyss",
    timeflow: true,
    choices: [
      {
        label: "深層循環に乗る",
        detail: "地球をひとまわりする、いちばん遅い流れ。",
        outcomes: [{ to: "OCEAN_UPWELL", weight: 2 }, { to: "OCEAN_DEEP" }],
      },
      {
        label: "熱水噴出孔へ",
        detail: "海底の割れ目から、黒い煙のような熱水が噴き出している。",
        outcomes: [{ to: "VENT" }],
      },
      {
        label: "海底の泥へ沈む",
        detail: "降り積もった生きものの死骸の中に、閉じ込められる。",
        outcomes: [{ to: "SEABED" }],
      },
    ],
  },
  {
    id: "VENT",
    name: "熱水噴出孔",
    place: "海底・熱水域",
    biome: "ocean",
    phase: "liquid",
    scene: "oceandeep",
    lines: [
      "300℃を超えているのに、圧力のせいで沸騰できない。",
      "岩の割れ目から地殻に潜り、熱せられ、また噴き出す。",
      "光のない場所に、それでも生きものが群れている。",
    ],
    hours: [YEAR * 5, YEAR * 300],
    km: [1, 60],
    salinity: "saline",
    depth: 2600,
    temperature: 340,
    tags: ["ocean", "abyss"],
    codex: "vent",
    choices: [
      {
        label: "上へ吹き上げられる",
        detail: "熱い水は軽い。何百mも、まっすぐ上昇する。",
        outcomes: [{ to: "OCEAN_UPWELL", weight: 2 }, { to: "OCEAN_DEEP" }],
      },
      {
        label: "地殻へ潜り込む",
        detail: "海底の下にも、水の道がある。",
        outcomes: [{ to: "GW_DEEP" }],
      },
    ],
  },
  {
    id: "SEABED",
    name: "海底の泥",
    place: "海底・堆積層",
    biome: "ocean",
    phase: "liquid",
    scene: "oceandeep",
    lines: [
      "上から、絶え間なく細かいものが降ってくる。",
      "一年に、わずか数ミリ。それが何万年も続いている。",
    ],
    hours: [YEAR * 1000, YEAR * 60000],
    km: [0, 20],
    depth: 4200,
    salinity: "saline",
    temperature: 2,
    tags: ["ocean", "abyss", "deepwater"],
    timeflow: true,
    choices: [
      {
        label: "圧力で押し出される",
        detail: "上に積もる重さが、泥の中の水を絞り出していく。",
        outcomes: [{ to: "OCEAN_DEEP", weight: 2 }, { to: "VENT" }],
      },
      {
        label: "プレートに運ばれる",
        detail: "海底そのものが、年に数センチずつ動いている。",
        outcomes: [{ to: "GW_DEEP", weight: 2 }, { to: "VENT" }],
      },
    ],
  },
  {
    id: "OCEAN_UPWELL",
    name: "湧昇",
    place: "外洋・湧昇域",
    biome: "ocean",
    phase: "liquid",
    scene: "oceancurrent",
    lines: [
      "何百年ぶりかに、上へ向かっている。",
      "深海の栄養を連れて上がるので、このあたりは生きものが多い。",
      "光が、だんだん見えてくる。",
    ],
    hours: [YEAR, YEAR * 60],
    km: [50, 3000],
    salinity: "saline",
    temperature: 12,
    tags: ["ocean", "current"],
    choices: [
      {
        label: "海面に出る",
        detail: "空気に触れる。千年ぶりに。",
        outcomes: [{ to: "OCEAN_SURFACE" }],
      },
      {
        label: "プランクトンに取り込まれる",
        detail: "栄養が上がってきた海は、緑色に濁るほど生きものが増える。",
        outcomes: [{ to: "PLANKTON" }],
      },
    ],
  },

  // ───────────────────────────────────────────── 大気へ
  {
    id: "VAPOR_RISE",
    name: "水蒸気",
    place: "大気",
    biome: "sky",
    phase: "gas",
    scene: "vapor",
    lines: [
      "形が、なくなった。",
      "丸くもなく、流れてもいない。ただの、目に見えない粒。",
      "上へ。空気が軽いほうへ。",
    ],
    hours: [0.5, 40],
    km: [1, 200],
    altitude: 800,
    temperature: 20,
    tags: ["vapor", "sky"],
    codex: "vapor",
    choices: [
      {
        label: "上昇を続ける",
        detail: "高く行くほど、空気は冷たくなる。",
        outcomes: [{ to: "VAPOR_HIGH" }],
      },
      {
        label: "風に流される",
        detail: "水蒸気は、大陸をいくつも越えて運ばれることがある。",
        outcomes: [{ to: "VAPOR_WIND" }],
      },
      {
        label: "低いところで漂う",
        detail: "地表近くに留まり、白いものになりはじめる。",
        outcomes: [{ to: "MIST" }],
      },
    ],
  },
  {
    id: "VAPOR_WIND",
    name: "大気の川",
    place: "上空・水蒸気帯",
    biome: "sky",
    phase: "gas",
    scene: "vapor",
    lines: [
      "空には、目に見えない水の帯が流れている。",
      "幅数百km、長さ数千km。運ばれている水の量は、大河をはるかに超える。",
    ],
    hours: [DAY, DAY * 12],
    km: [200, 5000],
    altitude: 3000,
    temperature: 6,
    tags: ["vapor", "sky"],
    codex: "atmosphericriver",
    choices: [
      {
        label: "山にぶつかる",
        detail: "行き止まり。持ち上げられ、冷やされ、雲になるしかない。",
        outcomes: [{ to: "VAPOR_HIGH" }],
      },
      {
        label: "内陸まで運ばれる",
        detail: "海から千km離れた場所にも、海の水は届く。",
        outcomes: [{ to: "VAPOR_HIGH", weight: 2 }, { to: "MIST" }],
      },
    ],
  },
  {
    id: "MIST",
    name: "霧",
    place: "地表付近",
    biome: "sky",
    phase: "liquid",
    scene: "vapor",
    lines: [
      "冷えて、また小さな水滴に戻った。",
      "浮いていられるほど、小さい。",
      "森の中に、白いものが満ちていく。",
    ],
    hours: [1, 30],
    km: [0.1, 20],
    altitude: 60,
    temperature: 9,
    tags: ["vapor", "sky"],
    codex: "mist",
    choices: [
      {
        label: "葉に捕まる",
        detail: "霧が木に当たると、雨が降っていなくても水が滴る。",
        outcomes: [
          { to: "FOREST_LEAF", weight: 2 },
          { to: "MTN_MOSS" },
          { to: "CITY_ROOF", when: inRegion("japan", "seasia") },
        ],
      },
      {
        label: "日が差して消える",
        detail: "霧が晴れる、というのは、水が見えなくなるということだ。",
        outcomes: [{ to: "VAPOR_RISE" }],
      },
      {
        label: "上へのぼる",
        detail: "地面が温まり、白い層ごと持ち上げられる。",
        outcomes: [{ to: "VAPOR_HIGH" }],
      },
    ],
  },
  {
    id: "VAPOR_HIGH",
    name: "上空",
    place: "上空 2,000m",
    biome: "sky",
    phase: "gas",
    scene: "sky",
    lines: [
      "空気が薄い。冷たい。",
      "気体でいられる限界が、近づいてくる。",
      "小さな塵に触れた瞬間、あなたはまた、水滴になる。",
    ],
    hours: [0.5, 20],
    km: [1, 300],
    altitude: 2000,
    temperature: 0,
    tags: ["vapor", "sky"],
    choices: [
      {
        label: "凝結する",
        detail: "気体から、液体へ。もう一度、丸くなる。",
        outcomes: [{ to: "CLOUD_RETURN" }],
      },
    ],
  },
  {
    id: "CLOUD_RETURN",
    name: "雲",
    place: "上空 2,400m",
    biome: "sky",
    phase: "liquid",
    scene: "cloud",
    lines: [
      "白い、巨大な空間。",
      "無数の水滴が、光の中を漂っている。",
      "最初と、同じ場所。",
    ],
    hours: [1, 40],
    km: [5, 400],
    altitude: 2400,
    temperature: 3,
    tags: ["sky"],
    codex: "cloud",
    ending: true,
    choices: [],
  },
];

export const NODES: Record<string, WaterNode> = Object.fromEntries(
  list.map((n) => [n.id, n]),
);

export const NODE_COUNT = list.length;

export const START_NODE = "CLOUD_BIRTH";

export function getNode(id: string): WaterNode {
  const node = NODES[id];
  if (!node) throw new Error(`unknown node: ${id}`);
  return node;
}

export { hasTag };
